import { portugalGuides } from './portugal-guides.mjs';
import { PRIVATE_CLIENTS_PAGE } from '../de-content/private-clients.mjs';
const link = (url, label) => `<a href="${url}">${label}</a>`;
const guide = (slug, label) => link(`/en/blog/${slug}/`, label);
const section = (id, title, body) => ({ id, title, body });
const p = text => `<p>${text}</p>`;
const enLocal = `<div class="cards">
<article><h3>Lagos · Western Algarve</h3><p>Coastal exposure, older town properties and homes managed while owners are abroad need their own review. ${guide('home-insurance-lagos','Lagos property guide')}.</p></article>
<article><h3>Tavira · Eastern Algarve</h3><p>Ria Formosa tidal-water wording, traditional roofs, renovation and salt corrosion are distinct questions. ${guide('home-insurance-tavira','Tavira property guide')}.</p></article>
<article><h3>Quinta do Lago · Vale do Lobo · Vilamoura</h3><p>Rebuilding specifications, pools, grounds, security and seasonal occupancy belong in the schedule. ${guide('home-insurance-loule-almancil','Loulé and Almancil guide')}.</p></article>
<article><h3>Cascais · Estoril · Lisbon</h3><p>Check private improvements against condominium cover and the actual reinstatement cost. ${guide('insuring-a-high-value-apartment-lisbon-cascais','Apartment insurance guide')}.</p></article>
<article><h3>Comporta · Melides</h3><p>Describe unusual materials, outbuildings, rebuilding methods and periods away before choosing a standard property policy. ${guide('home-insurance-comporta-melides','Comporta and Melides guide')}.</p></article></div>`;
const deLocal = `<div class="cards">
<article><h3>Lagos · Westalgarve</h3><p>Küstenlage, Altstadtgebäude und längere Abwesenheit gehören in die Risikobeschreibung. ${link('/de/versicherung-lagos/','Versicherung in Lagos')}.</p></article>
<article><h3>Tavira · Ostalgarve</h3><p>An der Ria Formosa zählen Gezeitenwasser, traditionelle Dächer, Sanierung und Korrosion. ${link('/de/versicherung-tavira/','Unser eigener Leitfaden für Tavira')}.</p></article>
<article><h3>Quinta do Lago · Vale do Lobo · Vilamoura</h3><p>Wiederaufbau, Außenanlagen, Sicherheit und saisonale Nutzung gemeinsam prüfen. ${link('/de/versicherung-quinta-do-lago/','Quinta do Lago')} · ${link('/de/versicherung-vilamoura/','Vilamoura')}.</p></article>
<article><h3>Cascais · Estoril · Lissabon</h3><p>Gemeinschaftseigentum und private Ausstattung benötigen klare Abgrenzungen. ${link('/de/versicherung-cascais/','Cascais')} · ${link('/de/versicherung-lissabon/','Lissabon')}.</p></article>
<article><h3>Comporta · Melides</h3><p>Bauweise, Wiederherstellung und Abwesenheit statt Kaufpreis als Ausgangspunkt. ${link('/de/versicherung-comporta/','Leitfaden Comporta')}.</p></article></div>`;
const reviewEN = section('review-process','How the review works',`<ol><li><strong>Map the household.</strong> Tell us who owns what, where it is used and who administers the insurance. A broad outline is enough to begin.</li><li><strong>Read what is already in place.</strong> We review schedules, wordings, renewal dates, declared use, values and gaps with you.</li><li><strong>Confirm a practical plan.</strong> We identify priorities, explain what needs underwriting and confirm available options and conditions before you decide.</li></ol><p>A review is not a promise of placement. Timing depends on the risk, documents and insurer response.</p>`);
const repEN = section('representatives','Managing insurance for a client or family?',p('A spouse or family member, Personal or Executive Assistant, Property, House or Estate Manager, Family Office or professional adviser can begin the review. Tell us your role and whether you are authorised to discuss the requirements. We agree the appropriate authority and information-sharing consent before discussing personal policy details; no documentary authority is requested on this first form.'));
const serviceEN = section('ongoing-service','Renewals, valuations and claims support',p('A change of home, a new acquisition, building work or a move between countries can matter before renewal. We help review values and declared use, prepare renewal information and communicate changes to the insurer. If a loss occurs, we assist with preparing and communicating the claim and remain involved during the claims process. The insurer decides the claim under the policy terms.'));
const portugal = {
  key:'en-pt', lang:'en', country:'Portugal', url:'/en/private-clients/', formName:'private-client-review-portugal',
  title:'Private Client Insurance in Portugal', eyebrow:'Private Clients · Portugal',
  standfirst:'One view of the risks across your household. Homes, possessions, vehicles, health and family responsibilities — reviewed together, with the detail each policy needs.',
  sections:[
    section('for-whom','For households with more to coordinate',p('Several residences, a home undergoing renovation, a collection that travels, family health cover or a property managed while you are abroad: complexity does not begin at a particular net worth. This service is for households whose insurance needs to be understood as a whole.')),
    section('policy-gaps','Separate policies can leave connected risks apart',p('Policies bought at different times can disagree about ownership, occupancy, values or who is insured. A generous contents total will not solve a restrictive single-item limit. A home policy may not follow a collection in transit. We start with these connections, then decide what each contract needs to do.')),
    section('coordination','What we coordinate',p('Property and contents; art, jewellery, watches and wine; vehicles and marine; health and international health; family liability; staff and property management. Life and mortgage-related protection can also form part of the household review. Coordination does not require every risk to sit with one insurer.')),
    section('residences','Several residences, sometimes several countries',p('We map each home’s ownership, use, occupation and management arrangements. Holiday letting, long empty periods and renovation must be declared separately. A household with Portuguese and Spanish interests can have one coordinated review, while each policy remains appropriate to its country. '+link('/en/private-clients-spain/','See the Spain service')+'.')),
    section('homes','High-value and non-standard homes',p('Rebuilding value is not purchase value. Quality of finishes, traditional construction, pools, gardens, retaining walls and outbuildings all affect the schedule. Underinsurance can reduce a partial settlement proportionally; any waiver of average or tolerance must be confirmed in the wording. Earthquake cover and its excess need an explicit decision.')+p('For individually underwritten Portuguese risks, the existing technical library explains Hiscox and Liberty Mutual through Innovarisk, and the role of specialist underwriting. Availability depends on the actual risk. Our choice to work with selected insurers is a service choice, not a regulatory restriction on market access. '+guide('how-specialist-risks-are-placed-portugal','How specialist placement works')+'.')),
    section('collections','Art, jewellery, watches and collections',p('Agree the basis of value before a loss. We review valuations, single-item limits, scheduled items, security requirements and possessions away from home. For art, restoration costs and residual loss in value matter alongside total loss; transit, loans and storage need explicit terms. For wine, discuss the inventory, valuation basis, storage conditions and spoilage.')+p('Agreed value, worldwide cover and restoration provisions are policy features to confirm, not automatic benefits. '+guide('valuations-portugal-who-what-how-often','Valuations')+' · '+guide('insuring-jewellery-watches-portugal','Jewellery and watches')+' · '+guide('wine-cellars-home-storage-valuation-cover','Wine cellars')+'.')),
    section('vehicles-marine','Collector vehicles and boats',p('For collector or high-value cars, review agreed value, use, storage and repair arrangements. For boats and yachts, the questions include hull value, navigation limits, marina liability requirements, crew, private use versus charter and lay-up. A household review identifies these requirements; each placement needs its own underwriting. '+guide('classic-collector-cars-portugal-matriculation-agreed-value','Collector cars')+' · '+guide('boat-insurance-portugal','Marine guide')+'.')),
    section('health','Health that follows your actual residence',p('Local and international health insurance answer different needs. We review residence, treatment geography, existing cover and continuity before looking at options. Eligibility, exclusions and medical underwriting are confirmed separately. Do not send medical records at first contact. '+link('/en/health-insurance-quote/','Health insurance in Portugal')+' · '+link('/en/international-health-insurance-portugal/','International health insurance')+'.')),
    section('liability','Family liability deserves its own discussion',p('Who is insured, where liability applies and which activities are excluded can matter more than the headline limit. Overseas expectations — including US liability expectations — may differ from Portuguese policy limits. '+guide('family-liability-cover-portugal','Family liability guide')+' · '+guide('us-buyers-property-cover-portugal','US buyer expectations')+'.')),
    section('staff-management','Household staff and property management',p('Tell us who employs staff, who holds keys and who checks the property during absences. Employment-related cover, owner liability and a manager’s own professional responsibilities are different questions. Renovation also changes the risk before the home is occupied. '+guide('domestic-staff-insurance-portugal','Domestic staff guide')+'.')),
    repEN,reviewEN,serviceEN,
    section('local','Local knowledge, property by property',enLocal),
    section('technical','Technical guides for the details',p('Use these depth layers when a particular exposure needs closer attention. Surveys, claims history, photographs, provenance and security details may be needed later; the first review begins with context.')+`<details><summary>Explore the Portugal technical library</summary><ul class="guide-list">${portugalGuides.map(g=>`<li>${link(g.url,g.label)}</li>`).join('')}</ul></details>`)
  ]
};
const spain = {
  key:'en-es', lang:'en', country:'Spain', url:'/en/private-clients-spain/', formName:'private-client-review-spain',
  title:'Private Client Insurance in Spain', eyebrow:'Private Clients · Spain',
  standfirst:'Bring your Spanish insurance into one household picture. Property, health, vehicles and family protection — coordinated around how you live, own and spend time in Spain.',
  sections:[
    section('for-whom','For households with more to coordinate',p('A Spanish second home, rental property, a move from another country or several policies administered by an assistant can call for a joined-up review. You do not need an unusual collection or a minimum net worth to benefit from a clearer insurance picture.')),
    section('policy-gaps','A policy for each purchase is not a household plan',p('A bank-arranged policy, cover bought when you moved and a motor renewal may each reflect a different moment in your life. We look for outdated values, missing people, undeclared rental use and gaps between contracts before discussing changes.')),
    section('coordination','What we coordinate',p('The review can bring together Spanish property, second-home and landlord requirements, health, motor, life and mortgage-related protection. Specialist assets and unusual exposures are assessed individually: we review the requirement and confirm what can be arranged.')),
    section('residences','Several homes, with country-appropriate policies',p('Non-resident ownership, long periods away, short-term letting and permanent occupation need different disclosures. If your household also has Portuguese interests, we coordinate the review across both countries without assuming one policy or insurer works in both. '+link('/en/private-clients/','See the Portugal service')+'.')),
    section('homes','High-value and non-standard Spanish property',p('We review rebuilding costs, ownership, occupancy, improvements and existing schedules. A higher purchase price does not establish the correct building sum insured. Unusual construction, a claims history or complex rental use needs insurer assessment; Portuguese specialist arrangements do not establish availability in Spain. '+guide('high-value-home-insurance-spain','High-value homes in Spain')+' · '+link('/en/landlord-insurance-spain/','Landlord insurance')+'.')),
    section('collections','Art, jewellery, watches and collections',p('Tell us about items whose values exceed a standard contents limit, collections moving between residences or valuables used away from home. We review valuations, security and territorial requirements and confirm what can be arranged. We do not assume agreed value, worldwide cover, art restoration or wine spoilage cover is available for a Spanish risk.')),
    section('vehicles-marine','Vehicles and marine requirements',p('For Spanish motor insurance, residence, registration, drivers and actual use form the starting point. '+link('/en/car-insurance-spain/','Our Spain motor page')+' explains the ordinary requirements. Collector vehicles and boats can be included in the review, but specialist availability and navigation or usage terms must be established separately.')),
    section('health','Health, international health and family protection',p('We review local versus international treatment needs, residence and existing health cover. Acceptance and benefits depend on the insurer and product. Life and mortgage-related cover should reflect today’s family commitments rather than an old loan balance. '+link('/en/health-insurance-spain/','Health')+' · '+link('/en/life-insurance-spain/','Life')+' · '+link('/en/mortgage-protection-spain/','Mortgage protection')+'.')),
    section('liability','Family liability across everyday activities',p('We examine who is insured, the activities and countries involved, exclusions and limits under existing contracts. Property-owner liability is not necessarily a complete answer to the household’s personal liabilities. Any additional requirement is reviewed for availability.')),
    section('staff-management','Staff, letting and remotely managed homes',p('A property manager’s involvement does not remove an owner’s disclosure responsibilities. We ask about occupancy checks, keyholders, staff, rentals and building works, and identify where a separate employment, liability or works arrangement needs to be confirmed.')),
    repEN,reviewEN,serviceEN,
    section('local','Portugal-based service for Spanish interests',p('Adler &amp; Rochefort is headquartered in Portugal and operates in Spain cross-border under Freedom of Services (LPS). There is no physical Spanish office. We coordinate the household’s requirements from Portugal; the actual availability of a Spanish insurer, product or coverage is confirmed for the case.')),
    section('technical','Spanish guidance, not Portuguese assumptions',`<ul class="guide-list"><li>${link('/en/home-insurance-spain/','Property and second homes in Spain')}</li><li>${link('/en/landlord-insurance-spain/','Rental and landlord exposures')}</li><li>${guide('high-value-home-insurance-spain','Higher-value Spanish property')}</li><li>${guide('insurance-review-expats-spain','Reviewing existing policies as a whole')}</li><li>${link('/en/blog/category/spain-private-clients/','All Spain Private Client guides')}</li></ul>`)
  ]
};
const german = {
  key:'de', lang:'de', country:'Portugal and Spain', url:'/de/private-clients/', formName:'private-client-review-de',
  title:'Private Clients in Portugal & Spanien', eyebrow:'Private Clients · Portugal & Spanien',
  standfirst:'Versicherung für Familien mit mehreren Immobilien, Ländern und komplexeren Risiken. Wir beginnen nicht mit dem Preis. Wir beginnen mit Ihrem Risiko.',
  sections:[
    section('fuer-wen','Wenn mehr als eine Police zusammenpassen muss',p('Mehrere Wohnsitze, ein Ferienhaus, eine Sammlung, internationale Krankenversicherung oder eine Immobilie, die während Ihrer Abwesenheit betreut wird: Entscheidend ist die Komplexität, nicht ein bestimmtes Vermögen. Wir betrachten den Versicherungsbedarf Ihrer Familie im Zusammenhang.')),
    section('luecken','Deutsche Erwartungen, iberische Versicherungsbedingungen',p('Eine aus Deutschland vertraute Bezeichnung bedeutet nicht denselben Leistungsumfang. Einzelgrenzen, Selbstbehalte, Leerstand, Haftpflicht und Unterversicherung verdienen einen Blick in die tatsächlichen Bedingungen. Verträge, die zu unterschiedlichen Zeitpunkten abgeschlossen wurden, können unterschiedliche Eigentümer, Nutzungen oder Werte abbilden.')),
    section('koordination','Was wir gemeinsam betrachten',p('Wohngebäude und Hausrat, Kunst und Sammlungen, Schmuck, Uhren und Wein, Fahrzeuge und Boote, Gesundheit, Familienhaftpflicht, Hausangestellte und Immobilienverwaltung. Auch Lebensversicherung und kreditbezogener Schutz können dazugehören. Wir koordinieren die Prüfung; die passende Absicherung wird für jedes Risiko gesondert bestätigt.')),
    section('wohnsitze','Mehrere Wohnsitze und Länder',p('Wo lebt die Familie, wem gehört welche Immobilie und wer nutzt sie? Zweitwohnsitz, Vermietung, längere Abwesenheit und laufende Bauarbeiten ändern die Anforderungen. Ein gemeinsamer Ansprechpartner ersetzt keine landesgerechte Police. Die Betreuung eines Haushalts in beiden Ländern bedeutet nicht, dass jeder Versicherer oder Tarif in beiden verfügbar ist.')),
    section('immobilien','Wiederaufbauwert statt Kaufpreis',p('Grundstückspreis und Lage bestimmen nicht die Kosten eines Wiederaufbaus. Besondere Materialien, historische Bauteile und Außenanlagen gehören in die Bewertung. Unterversicherung kann auch Teilschäden anteilig kürzen. Einen Verzicht auf diese Kürzung, Toleranzen und eine Erdbebendeckung samt Selbstbehalt prüfen wir ausdrücklich. '+link('/de/hausversicherung-portugal/','Hausversicherung in Portugal')+'.')),
    section('sammlungen','Kunst, Schmuck, Uhren und Sammlungen',p('Wir prüfen Einzelgrenzen, Gutachten, vereinbarte Werte, Sicherheitsvorgaben und Besitz außerhalb des Hauses. Bei Kunst können Restaurierung und verbleibende Wertminderung wichtig sein; bei Wein Lagerung, Inventar und Verderb. Transport und Leihgaben brauchen eine eigene Prüfung. Für Portugal bietet unsere technische Bibliothek mehr Tiefe; für Spanien bestätigen wir zuerst, was für das konkrete Risiko arrangiert werden kann.')),
    section('fahrzeuge-boote','Fahrzeuge und Boote',p('Oldtimer und hochwertige Fahrzeuge werfen Fragen nach vereinbartem Wert, Nutzung, Zulassung und Unterbringung auf. Bei Booten zählen Fahrtgebiet, Liegeplatz, Haftpflicht und private Nutzung oder Charter. Spezialdeckungen werden individuell geprüft und nicht aus dem Angebot eines anderen Landes abgeleitet. '+guide('classic-collector-cars-portugal-matriculation-agreed-value','Oldtimer in Portugal (Englisch)')+' · '+guide('boat-insurance-portugal','Boote in Portugal (Englisch)')+'.')),
    section('gesundheit','Gesundheit und internationale Krankenversicherung',p('Wohnsitz, Behandlungsland, bestehende Absicherung und Kontinuität stehen vor der Tarifauswahl. Lokale und internationale Krankenversicherung sind nicht austauschbar. Annahme und Ausschlüsse werden gesondert geprüft; medizinische Unterlagen gehören nicht in das Erstkontaktformular. '+link('/de/krankenversicherung-portugal/','Krankenversicherung Portugal')+' · '+link('/en/health-insurance-spain/','Spanien (Englisch)')+'.')),
    section('haftpflicht','Familienhaftpflicht bewusst prüfen',p('Welche Personen, Tätigkeiten und Länder sind eingeschlossen? Eine Gebäudehaftpflicht ersetzt nicht automatisch die aus Deutschland erwartete Privathaftpflicht. Wir prüfen bestehende Grenzen und Ausschlüsse und klären den ergänzenden Bedarf. '+guide('family-liability-cover-portugal','Familienhaftpflicht Portugal (Englisch)')+'.')),
    section('verwaltung','Hausangestellte und betreute Immobilien',p('Wer beschäftigt Personal, hält Schlüssel und kontrolliert ein unbewohntes Haus? Eigentümerpflichten, Beschäftigungsrisiken und die berufliche Verantwortung der Verwaltung sind getrennte Themen. Renovierungen und Vermietung müssen zur tatsächlichen Nutzung in der Police passen.')),
    section('vertretung','Sie organisieren die Versicherung für eine Familie?',p('Ehepartner, Familienangehörige, Personal oder Executive Assistants, Haus- und Immobilienverwaltung, Estate Manager, Family Offices und professionelle Berater können die Analyse anstoßen. Geben Sie Ihre Rolle und Ihre Berechtigung zur Besprechung des Bedarfs an. Vor dem Austausch persönlicher Vertragsdetails klären wir die passende Berechtigung und Einwilligung zur Informationsweitergabe. Beim Erstkontakt sind keine Vollmachtsdokumente nötig.')),
    section('ablauf','So läuft die Versicherungsanalyse ab','<ol><li><strong>Überblick schaffen.</strong> Haushaltsstruktur, Länder, Immobilien und Ansprechpartner erfassen.</li><li><strong>Bestehenden Schutz prüfen.</strong> Später Vertragsunterlagen, Werte, Nutzungen und Verlängerungen zusammenführen.</li><li><strong>Prioritäten vereinbaren.</strong> Lücken und Rückfragen erklären, Versicherbarkeit und Bedingungen klären, dann entscheiden Sie.</li></ol><p>Die Dauer hängt von Unterlagen, Risiko und Rückmeldung des Versicherers ab. Eine Analyse ist keine Deckungszusage.</p>'),
    section('betreuung','Verlängerungen, Bewertungen und Schadenbegleitung',p('Neue Anschaffungen, Umzüge und Bauarbeiten können schon vor der nächsten Verlängerung relevant sein. Wir unterstützen bei der Aktualisierung und bei der Vorbereitung und Kommunikation eines Schadens. Wir bleiben während des Schadenprozesses beteiligt; die Entscheidung über die Leistung trifft der Versicherer nach den Vertragsbedingungen.')),
    section('portugal','Portugal: lokale Unterschiede ernst nehmen',deLocal+p('Die bestehende '+link('/de/private-clients-portugal/','Portugal-Seite für komplexe Risiken')+' bleibt als vertiefende Fachseite erhalten.')),
    section('spanien','Spanien: Teil derselben Haushaltsanalyse',p('Wir betreuen spanische Versicherungsbedürfnisse grenzüberschreitend aus Portugal im Rahmen der Dienstleistungsfreiheit (LPS), ohne spanische Niederlassung oder physisches Büro. Ausgangspunkte sind Immobilien, nicht ständig bewohnte Zweitwohnsitze, Vermietung, Gesundheit, Kfz, Leben und kreditbezogener Schutz.')+p('Für Kunst, Schmuck, Sammlungen und ungewöhnlich hohe Risiken prüfen wir den Bedarf und bestätigen, was arrangiert werden kann. Portugiesische Spezialkapazität ist kein Nachweis spanischer Verfügbarkeit. Unsere vorhandenen Spanien-Leitfäden sind auf Englisch: '+link('/en/home-insurance-spain/','Immobilien')+' · '+link('/en/landlord-insurance-spain/','Vermietung')+' · '+link('/en/car-insurance-spain/','Kfz')+' · '+link('/en/life-insurance-spain/','Leben')+' · '+link('/en/mortgage-protection-spain/','Kreditschutz')+'.')),
    section('wissen','Fachwissen für die nächste Frage',`<ul class="guide-list"><li>${link('/de/private-clients-portugal/','Portugal: Spezialrisiken und individuelle Zeichnung')}</li><li>${guide('valuations-portugal-who-what-how-often','Bewertungen in Portugal (Englisch)')}</li><li>${guide('worldwide-cover-personal-possessions-portugal','Besitz außerhalb des Wohnsitzes (Englisch)')}</li><li>${guide('insurance-review-expats-spain','Spanische Policen gemeinsam prüfen (Englisch)')}</li></ul>`)
  ]
};
const dePortugal = {
 key:'de-pt',lang:'de',country:'Portugal',url:'/de/private-clients-portugal/',formName:'private-client-review-de',
 title:'Private Clients Portugal: komplexe Risiken versichern',eyebrow:'Private Clients · Fachseite Portugal',
 standfirst:'Vertiefung für portugiesische Immobilien, Sammlungen und individuell zu prüfende Risiken. Für die gemeinsame Haushaltsanalyse in Portugal und Spanien beginnen Sie in unserem Private-Client-Hub.',
 sections:[section('haushalt','Zuerst der Haushalt, dann die einzelne Deckung',p(link('/de/private-clients/','Private Clients Portugal & Spanien')+' verbindet diese Detailprüfung mit Gesundheit, Haftpflicht, mehreren Wohnsitzen und der Zusammenarbeit mit einer bevollmächtigten Ansprechperson.'))],
 // The existing owner remains the source of technical content; do not fork it.
 technicalHTML:PRIVATE_CLIENTS_PAGE.sections,
};
const tavira = {
 key:'de-tavira',lang:'de',country:'Portugal',url:'/de/versicherung-tavira/',formName:'private-client-review-de',
 title:'Hausversicherung in Tavira und der Ostalgarve',eyebrow:'Portugal · Tavira & Ostalgarve',
 standfirst:'Ria Formosa, traditionelle Gebäude und Sanierung: In Tavira sind andere Fragen entscheidend als an der Klippenküste der Westalgarve.',
 sections:[
 section('ria-formosa','Ria Formosa: Regenwasser ist nicht Gezeitenwasser',p('Bei Immobilien in Santa Luzia, Cabanas, Conceição und am Lagunenrand sollte die Prüfung zwischen Regenwasserüberschwemmung und eindringendem Meer- oder Gezeitenwasser unterscheiden. Eine Police kann das eine einschließen und das andere ausschließen. Für Erdgeschossräume und tiefer liegende Lagerflächen benötigen Sie eine ausdrückliche Klärung der Bedingungen.')+p('Ein hoher Grundwasserstand, aufsteigende Feuchtigkeit und Kondensation sind andere Ursachen als ein plötzliches Leitungsleck. Lassen Sie die Ursache klären, bevor ein Schaden als versichertes Ereignis eingeordnet wird. Wartung und allmähliche Einwirkung sind regelmäßig Gegenstand von Ausschlüssen.')),
 section('altstadt','Altstadt: den tatsächlichen Wiederaufbau bewerten',p('Im historischen Tavira rund um Burg, Igreja de Santa Maria und Gilão kommen traditionelle Kalkmörtel, Holzstrukturen und die charakteristischen vierseitigen Ziegeldächer vor. Die Wiederherstellung eines telhado de tesouro oder einer traditionellen Fassade kann spezialisierte Handwerker und Materialien erfordern. Ein pauschaler moderner Quadratmeterpreis kann deshalb zu wenig sein.')+p('Wenn Schutzvorgaben bestimmte Materialien oder Verfahren verlangen, prüfen Sie, ob die Police diese Wiederherstellung berücksichtigt. Ein moderner Ersatz zum Standardpreis muss die tatsächlichen Kosten nicht decken. '+guide('renovating-listed-heritage-property-portugal','Sanierung historischer Gebäude (Englisch)')+'.')),
 section('sanierung','Sanierung und Übergang zur Wohnnutzung',p('Ein leeres Haus mit laufenden Bauarbeiten ist kein gewöhnlich bewohntes Wohngebäude. Klären Sie vor Baubeginn, ob eine ausdrückliche Erweiterung oder eine Bauleistungs- und Baustellenhaftpflichtlösung benötigt wird: Arbeiten, gelagerte Materialien und Verantwortlichkeiten gehören in die Prüfung.')+p('Achten Sie besonders auf den Übergang: Wann endet die Deckung des Bauunternehmens, wann ist die Fertigstellung vorgesehen und ab wann akzeptiert ein Wohngebäudeversicherer das Risiko? Offene Genehmigungen oder ausstehende Nutzungsunterlagen sollten vorab angesprochen werden. Eine lückenlose Lösung muss schriftlich bestätigt werden; sie entsteht nicht automatisch bei Schlüsselübergabe.')),
 section('salz','Salz, Wind und Wartungsnachweise',p('Salzhaltige Luft betrifft Fensterrahmen, Geländer, Dachbefestigungen, Außeninstallationen, Klimaanlagen und Pooltechnik. Bei einem Sturmschaden kann die Frage entstehen, ob Wind oder bereits vorhandene Korrosion die Ursache war. Verschleiß ist nicht dasselbe wie ein plötzliches versichertes Ereignis.')+p('Dokumentierte Kontrollen, Fotos, Wartungsrechnungen und rechtzeitiger Austausch korrodierter Teile helfen, den Zustand des Hauses nachvollziehbar zu machen. Wenn Sie im Ausland wohnen, vereinbaren Sie mit der Verwaltung, wer diese Kontrollen übernimmt.')),
 section('zweitwohnsitz','Zweitwohnsitz und Vermietung offen beschreiben',p('Geben Sie an, wie lange das Haus leer steht, wer es kontrolliert und ob Feriengäste oder Mieter es nutzen. Leerstandsfristen, Sicherungsvorgaben und erlaubte Nutzungen unterscheiden sich je nach Vertrag. Sammlungen und wertvolle Gegenstände sollten mit Einzelgrenzen und Lagerbedingungen zusammen geprüft werden.')),
 section('vorbereitung','Was für die spätere Prüfung hilft','<ul><li>Bauweise, Zustand und vorhandene Unterlagen zur Immobilie.</li><li>Nähe zur Lagune, Nutzung von Erdgeschoss und tieferen Räumen.</li><li>Sanierungsplan, Zeitplan und Übergang zur Wohnnutzung.</li><li>Wiederaufbaukosten, besondere Bauteile und mögliche Schutzvorgaben.</li><li>Nutzung, Abwesenheit, Betreuung und bisherige Schäden.</li></ul><p>Für den ersten Kontakt genügt ein kurzer Überblick. Unterlagen besprechen wir anschließend.</p>'),
 section('weiterlesen','Tavira im größeren Haushaltsbild',p('Dieser Leitfaden adaptiert die vorhandene '+guide('home-insurance-tavira','englische Tavira-Fachseite')+'. Für die Westalgarve gibt es einen eigenen '+link('/de/versicherung-lagos/','Lagos-Leitfaden')+'. Zur koordinierten Prüfung mehrerer Häuser und Länder: '+link('/de/private-clients/','Private Clients Portugal & Spanien')+'.'))
 ]
};
export const PRIVATE_CLIENT_PAGES = [portugal,spain,german,dePortugal,tavira];
export const privateClientPage = url => PRIVATE_CLIENT_PAGES.find(p=>p.url===url);
