#!/usr/bin/env node
/**
 * Block 1 — blog architecture.
 *
 * Generates, from `data/articles.json` alone:
 *   /blog/                      index, 12 articles per page
 *   /blog/pagina/N/             pagination
 *   /blog/categoria/{slug}/     the PT category pages (paginated the same way)
 *   /en/blog/category/{slug}/   the EN category pages (paginated the same way)
 *   /blog/feed.xml              RSS 2.0
 *   /en/blog/                   EN index, 12 per page
 *   /en/blog/page/N/            EN pagination
 *   /en/blog/feed.xml           EN RSS 2.0
 *
 * The EN taxonomy was signed off in Phase 3 and now lives in
 * scripts/build-articles-data.mjs alongside the PT one, so the two category
 * trees are generated by the same code path from the same derived file.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import {
  ROOT,
  PUBLIC,
  ORIGIN,
  page,
  writePage,
  writeSharedStylesheet,
  esc,
  jsonLd,
  breadcrumbLd,
  ORGANIZATION,
} from './lib/chrome.mjs';
import { grid, breadcrumbHtml, pagination, metaHead, CTA_PT, CTA_EN } from './lib/blog-parts.mjs';

const PER_PAGE = 12;
const data = JSON.parse(await readFile(join(ROOT, 'data', 'articles.json'), 'utf8'));
const CATEGORIES = data.categories.pt;
const EN_CATEGORIES = data.categories.en;

const byDateDesc = (a, b) => (b.published || '').localeCompare(a.published || '');
const ptArticles = data.articles.pt.filter((a) => a.status === 'published').sort(byDateDesc);
const enArticles = data.articles.en.filter((a) => a.status === 'published').sort(byDateDesc);

const written = [];
const chunk = (arr) => {
  const out = [];
  for (let i = 0; i < arr.length; i += PER_PAGE) out.push(arr.slice(i, i + PER_PAGE));
  return out.length ? out : [[]];
};

// ---------------------------------------------------------------------------
// Copy
// ---------------------------------------------------------------------------

const BLOG_INTRO = `<p>Esta é a secção de análise da Adler &amp; Rochefort. Reunimos aqui o que aprendemos a ler nas apólices que passam pelas nossas mãos: as coberturas que a lei portuguesa impõe, as que as seguradoras oferecem como opção e as que quase ninguém contrata até precisar delas. Escrevemos sobre seguro automóvel e TVDE, hotelaria e alojamento local, riscos empresariais, habitação e saúde — sempre com o enquadramento legal aplicável em Portugal e a referência ao diploma ou norma que o sustenta.</p>
<p>Não publicamos comparações de preços nem rankings de seguradoras. Publicamos o que muda a decisão: uma exclusão redigida de forma ambígua, um capital seguro desatualizado, uma atividade declarada que já não corresponde à que exerce. Cada artigo indica a data de publicação e, quando o enquadramento legal mudou entretanto, a data da última atualização — a legislação de seguros em Portugal altera-se com frequência e um texto sem data vale pouco. Se um artigo lhe levantar uma dúvida sobre a sua própria apólice, fale connosco — somos um mediador de seguros registado na ASF com o n.º 425591790/3 e a análise não tem custo.</p>`;

const CATEGORY_INTROS = {
  'seguros-auto-tvde': `<p>O seguro automóvel é o único seguro obrigatório para quem circula em Portugal, mas a obrigação legal — responsabilidade civil perante terceiros — é também a cobertura mais estreita que existe. Tudo o resto (danos próprios, quebra isolada de vidros, assistência em viagem, veículo de substituição, proteção do condutor) é facultativo e é aí que as apólices se distinguem umas das outras.</p>
<p>Para quem conduz em TVDE a questão muda de natureza. A atividade de transporte individual e remunerado de passageiros em veículo descaracterizado está regulada pela Lei n.º 45/2018 e exige uma apólice que cubra o transporte remunerado de passageiros. Uma apólice particular comum não cobre essa utilização: em caso de sinistro com passageiro a bordo, a seguradora pode recusar o pagamento por agravamento não declarado do risco. O mesmo raciocínio aplica-se às frotas empresariais, onde a titularidade dos veículos, o número de condutores e a existência de utilização mista alteram por completo a forma como o risco é subscrito.</p>
<p>Nesta categoria reunimos os artigos sobre seguro automóvel particular, TVDE, frotas de empresa e as situações intermédias — condutores expatriados com carta estrangeira, veículos importados, viaturas afetas a duas atividades. O objetivo é o mesmo em todos: identificar antes do sinistro aquilo que a apólice não cobre.</p>`,

  'hotelaria-turismo': `<p>Alojamento local, hotelaria e restauração partilham um traço que os distingue de quase todos os outros negócios: recebem pessoas dentro do espaço explorado. Isso transforma a responsabilidade civil de exploração numa cobertura central e não acessória, e é essa a razão pela qual o legislador português a tornou obrigatória para o alojamento local através do Decreto-Lei n.º 76/2024, que revê o regime anterior fixado no Decreto-Lei n.º 128/2014.</p>
<p>Na prática, os riscos concentram-se em pontos previsíveis: quedas em zonas molhadas, piscinas sem vedação conforme, intoxicações alimentares, incêndio na cozinha, danos causados por hóspedes ao edifício e a terceiros, e a perda de exploração durante o período de reparação. A cobertura de perda de exploração é frequentemente a que falta — um restaurante que fecha três meses por incêndio recebe a indemnização pelos danos materiais, mas suporta sozinho a receita que deixou de gerar e os salários que continuou a pagar.</p>
<p>Há ainda a questão da atividade declarada. Uma moradia registada como alojamento local mas segurada como habitação própria permanente não está coberta enquanto explorada turisticamente. É uma divergência silenciosa, que só se manifesta no momento da participação do sinistro.</p>
<p>Os artigos desta categoria cobrem o regime legal do alojamento local, os seguros obrigatórios em hotelaria e turismo, sinistros típicos em bares e restaurantes e a articulação entre a apólice do proprietário e a do explorador.</p>`,

  'seguros-empresariais': `<p>Uma empresa em Portugal tem obrigações de seguro que variam com a atividade, mas há um núcleo comum: o seguro de acidentes de trabalho é obrigatório para todos os trabalhadores por conta de outrem, e os trabalhadores independentes têm um regime próprio de proteção. A partir daí, a lei impõe seguros específicos a atividades reguladas — construção, mediação, transporte, saúde, entre outras — e deixa o resto à avaliação de cada empresa.</p>
<p>O multirriscos empresarial é a apólice que agrega a proteção do património: edifício, recheio, equipamento, mercadoria, e normalmente responsabilidade civil de exploração. A discussão relevante raramente é o prémio; é o capital seguro. Um capital desatualizado ativa a regra proporcional, e uma empresa segurada por metade do valor de reconstrução recebe metade da indemnização mesmo num sinistro parcial.</p>
<p>Ao lado disso ganharam peso riscos que há dez anos eram marginais. A responsabilidade civil profissional cobre o erro técnico e o conselho errado. A responsabilidade de administradores e gerentes (D&amp;O) responde por decisões de gestão. O seguro de riscos cibernéticos cobre o ransomware, a interrupção de atividade e a notificação à Comissão Nacional de Proteção de Dados após uma violação de dados pessoais — uma obrigação que o RGPD impõe em 72 horas.</p>
<p>Reunimos aqui as análises sobre seguros obrigatórios, multirriscos, responsabilidade civil, riscos cibernéticos, obras e construção, e a revisão periódica de carteiras empresariais.</p>`,

  'habitacao-particulares': `<p>Em Portugal só um seguro relacionado com a casa é verdadeiramente obrigatório: o seguro de incêndio sobre a fração e sobre as partes comuns, imposto pelo Código Civil e pelo regime da propriedade horizontal. Todo o resto — danos por água, fenómenos sísmicos, roubo, responsabilidade civil familiar, recheio, quebra de vidros — depende do multirriscos habitação que cada proprietário decidir contratar. Quem tem crédito à habitação contrata normalmente a apólice exigida pelo banco, e é aí que começa a maior parte dos problemas: essa apólice protege primeiro a garantia do banco e só depois o património de quem lá vive.</p>
<p>Os pontos que mais vezes falham são três. O capital do edifício, que deve corresponder ao custo de reconstrução e não ao valor de mercado nem ao valor da escritura. O recheio, quase sempre subestimado, e onde os bens de valor elevado exigem declaração individual. E a cláusula de desocupação, que suspende ou limita coberturas em casas vazias durante períodos prolongados — uma situação comum em segundas habitações.</p>
<p>Há ainda o enquadramento documental: legalização do imóvel, licença de utilização, obras não participadas às finanças. Uma divergência entre a realidade física do imóvel e o que consta na apólice ou na caderneta predial pode reduzir ou anular a indemnização.</p>
<p>Esta categoria agrupa os artigos sobre multirriscos habitação, risco de título na compra e a proteção do património familiar. As partes comuns e as obrigações do administrador têm categoria própria, em <a href="/blog/categoria/condominios/">Seguros de Condomínio</a>.</p>`,

  condominios: `<p>Num edifício em propriedade horizontal há sempre dois seguros a coexistir, e confundi-los é a origem da maior parte dos conflitos que chegam a tribunal. O condomínio segura as partes comuns — estrutura, cobertura, fachada, caixa de escadas, elevador, canalizações gerais. Cada condómino segura a sua fração. O seguro de incêndio sobre umas e outras é obrigatório por força do Código Civil e do regime da propriedade horizontal, e a sua contratação para as partes comuns é competência do administrador.</p>
<p>O ponto que falha com mais frequência é o capital. O valor seguro das partes comuns deve corresponder ao custo de reconstrução do edifício, não ao valor patrimonial tributário nem à soma das permilagens escrituradas. Quando está desatualizado — e depois de vários anos de subida dos custos de construção está quase sempre — aplica-se a regra proporcional: numa participação de danos por água de dez mil euros, um edifício segurado por metade do valor de reconstrução recebe metade. A diferença é repartida pelos condóminos em assembleia.</p>
<p>A segunda zona cinzenta é a fronteira entre apólices. Uma infiltração que nasce numa conduta comum e danifica o recheio de uma fração envolve as duas apólices e, frequentemente, duas seguradoras diferentes com peritagens independentes. Saber de antemão quem responde por quê — e ter a ata que o documente — encurta processos que de outro modo se arrastam.</p>
<p>Reunimos aqui os artigos sobre a obrigatoriedade do seguro de condomínio, as responsabilidades do administrador, a atualização de capitais e a articulação entre a apólice do condomínio e a de cada fração.</p>`,

  'seguros-saude': `<p>O acesso à saúde em Portugal assenta no Serviço Nacional de Saúde, e o seguro de saúde privado não o substitui: complementa-o, sobretudo no tempo de espera para consulta de especialidade, meios complementares de diagnóstico e cirurgia programada. É essa a comparação útil — não «seguro contra SNS», mas o que cada um resolve melhor e a que custo.</p>
<p>A variável que determina quase tudo numa apólice de saúde é a forma como trata as doenças pré-existentes. A regra dominante no mercado português é a exclusão: patologias diagnosticadas ou sintomáticas antes da adesão ficam de fora, muitas vezes de forma vitalícia. Existem exceções e caminhos alternativos, nomeadamente as mutualidades e alguns planos de grupo, mas cada um traz condições próprias de admissão. A declaração inicial de saúde é o documento crítico de todo o processo: uma omissão, ainda que involuntária, permite à seguradora anular o contrato ou recusar o sinistro.</p>
<p>A seguir vêm os períodos de carência, que suspendem coberturas nos primeiros meses e são mais longos em parto e estomatologia; os copagamentos e franquias; e os limites anuais por cobertura, que raramente são visíveis na comparação comercial.</p>
<p>Nesta categoria analisamos planos de saúde individuais e de grupo, doenças pré-existentes, carências, rede convencionada e a articulação com o SNS.</p>`,

  'tecnologia-parcerias': `<p>A mediação de seguros mudou menos na cobertura do que na gestão. O que antes era uma pasta de apólices em papel é hoje um problema de dados: saber que apólices tem uma empresa, quando renovam, que capitais estão desatualizados, que atividade está declarada em cada uma e onde há duplicação de coberturas entre contratos assinados em anos diferentes.</p>
<p>É esse o campo desta categoria. Escrevemos sobre a tecnologia que usamos para gerir carteiras — a plataforma Os Meus Seguros e o trabalho de consolidação documental que a alimenta —, sobre a forma como a informação estruturada altera a conversa de renovação, e sobre o que a inteligência artificial faz e não faz de útil na análise de condições gerais.</p>
<p>Reunimos também aqui os artigos sobre parcerias e canais de referência. A Adler &amp; Rochefort trabalha com mediadores imobiliários, gestores de alojamento local, escritórios de contabilidade e empresas de relocation, e a mecânica dessas relações — quem apresenta o cliente, quem faz a análise técnica, como se estrutura a comissão e o que a regulação da ASF permite — é matéria que interessa a quem pondera trabalhar connosco.</p>
<p>Por fim, incluímos as peças mais institucionais: percurso, formação, seguradoras parceiras e a experiência acumulada no setor do turismo que deu origem à especialização em hotelaria.</p>`,
};

const CATEGORY_META = {
  'seguros-auto-tvde': {
    title: 'Seguros Automóvel e TVDE | Insights | Adler & Rochefort',
    description:
      'Análises sobre seguro automóvel, TVDE e frotas em Portugal: obrigações legais, coberturas facultativas e exclusões que só aparecem no sinistro.',
  },
  'hotelaria-turismo': {
    title: 'Hotelaria, Turismo e Alojamento Local | Insights | Adler & Rochefort',
    description:
      'Seguros obrigatórios no alojamento local e na hotelaria em Portugal, responsabilidade civil de exploração, perda de exploração e sinistros típicos.',
  },
  'seguros-empresariais': {
    title: 'Seguros Empresariais | Insights | Adler & Rochefort',
    description:
      'Multirriscos empresarial, responsabilidade civil, D&O, riscos cibernéticos e acidentes de trabalho: o que a lei portuguesa exige e o que fica de fora.',
  },
  'habitacao-particulares': {
    title: 'Habitação e Particulares | Insights | Adler & Rochefort',
    description:
      'Multirriscos habitação e património familiar: capital de reconstrução, cláusula de desocupação e o que o seguro do banco não protege.',
  },
  condominios: {
    title: 'Seguros de Condomínio | Insights | Adler & Rochefort',
    description:
      'Seguro de condomínio em Portugal: obrigatoriedade, responsabilidades do administrador, capitais de reconstrução e a fronteira entre partes comuns e fração.',
  },
  'seguros-saude': {
    title: 'Seguros de Saúde | Insights | Adler & Rochefort',
    description:
      'Seguro de saúde em Portugal: doenças pré-existentes, carências, copagamentos, rede convencionada e articulação com o SNS.',
  },
  'tecnologia-parcerias': {
    title: 'Tecnologia e Parcerias | Insights | Adler & Rochefort',
    description:
      'Gestão digital de apólices, a plataforma Os Meus Seguros, parcerias de referência e o percurso da Adler & Rochefort na mediação de seguros.',
  },
};

// ---------------------------------------------------------------------------
// PT — /blog/ and /blog/pagina/N/
// ---------------------------------------------------------------------------

const categoryNav = (activeSlug) => {
  const chips = [
    `<a class="category-chip${activeSlug ? '' : ' active'}" href="/blog/">Todos<span class="category-chip-count">${ptArticles.length}</span></a>`,
    ...CATEGORIES.map((c) => {
      const n = ptArticles.filter((a) => a.category === c.slug).length;
      return `<a class="category-chip${activeSlug === c.slug ? ' active' : ''}" href="/blog/categoria/${c.slug}/">${esc(c.short)}<span class="category-chip-count">${n}</span></a>`;
    }),
  ];
  return `<nav class="category-nav" aria-label="Categorias">${chips.join('')}</nav>`;
};

const itemListLd = (items, name) => ({
  '@context': 'https://schema.org',
  '@type': 'ItemList',
  name,
  itemListElement: items.map((a, i) => ({
    '@type': 'ListItem',
    position: i + 1,
    url: ORIGIN + a.url,
    name: a.title,
  })),
});

async function buildListing({
  articles,
  basePath,
  pageHref,
  h1,
  intro,
  meta,
  crumbs,
  nav,
  lang,
  cta,
  collectionName,
  feed,
}) {
  const pages = chunk(articles);
  for (let i = 0; i < pages.length; i++) {
    const n = i + 1;
    const path = n === 1 ? basePath : pageHref(n);
    const suffix = n === 1 ? '' : lang === 'en' ? ` — page ${n}` : ` — página ${n}`;
    const head = metaHead({
      title: n === 1 ? meta.title : meta.title.replace(' | ', `${suffix} | `),
      description: meta.description,
      canonical: path,
      prev: n === 2 ? basePath : n > 2 ? pageHref(n - 1) : undefined,
      next: n < pages.length ? pageHref(n + 1) : undefined,
      robots: 'index, follow',
      feed,
    });
    const body = [
      breadcrumbHtml(crumbs),
      `<header class="page-head">
  <div class="section-eyebrow">Insights</div>
  <h1 class="section-title" style="margin-bottom:28px;">${h1}</h1>
  <div class="page-intro">${n === 1 ? intro : `<p>${esc(collectionName)}${suffix}.</p>`}</div>
</header>`,
      nav,
      grid(pages[i]),
      pagination(n, pages.length, (x) => (x === 1 ? basePath : pageHref(x)), lang),
      cta,
    ].join('\n\n');

    const bodyEnd = [
      jsonLd({ '@context': 'https://schema.org', '@graph': [ORGANIZATION] }),
      jsonLd(breadcrumbLd(crumbs.map((c) => ({ name: c.name, url: c.url })))),
      jsonLd(itemListLd(pages[i], collectionName)),
    ].join('\n');

    written.push(await writePage(path.replace(/^\/|\/$/g, ''), page({ lang: lang === 'en' ? 'en-GB' : 'pt-PT', head, body, bodyEnd })));
  }
  return pages.length;
}

await writeSharedStylesheet();

const ptPages = await buildListing({
  articles: ptArticles,
  basePath: '/blog/',
  pageHref: (n) => `/blog/pagina/${n}/`,
  h1: 'Insights &mdash; <em>Análises sobre seguros em Portugal</em>',
  intro: BLOG_INTRO,
  meta: {
    title: 'Insights — Análises sobre seguros em Portugal | Adler & Rochefort',
    description:
      'Análises sobre seguros em Portugal: obrigações legais, coberturas essenciais e exclusões — automóvel e TVDE, alojamento local, empresas, habitação e saúde.',
  },
  crumbs: [
    { name: 'Início', url: '/' },
    { name: 'Insights', url: '/blog/' },
  ],
  nav: categoryNav(null),
  lang: 'pt',
  cta: CTA_PT,
  collectionName: 'Insights',
});

// ---------------------------------------------------------------------------
// PT category pages
// ---------------------------------------------------------------------------

for (const c of CATEGORIES) {
  const items = ptArticles.filter((a) => a.category === c.slug);
  const landing = c.landing
    ? `\n<p><strong>Precisa de uma proposta?</strong> Veja a página de <a href="${c.landing}">${esc(c.landingLabel)}</a>.</p>`
    : '';
  await buildListing({
    articles: items,
    basePath: `/blog/categoria/${c.slug}/`,
    pageHref: (n) => `/blog/categoria/${c.slug}/pagina/${n}/`,
    h1: esc(c.title),
    intro: CATEGORY_INTROS[c.slug] + landing,
    meta: CATEGORY_META[c.slug],
    crumbs: [
      { name: 'Início', url: '/' },
      { name: 'Insights', url: '/blog/' },
      { name: c.title, url: `/blog/categoria/${c.slug}/` },
    ],
    nav: categoryNav(c.slug),
    lang: 'pt',
    cta: CTA_PT,
    collectionName: c.title,
  });
}

// ---------------------------------------------------------------------------
// EN — /en/blog/ and /en/blog/category/{slug}/
// ---------------------------------------------------------------------------

const EN_INTRO = `<p>This is where Adler &amp; Rochefort writes up what we learn from the policies that cross our desk. The audience is the one we actually serve in English: people who have moved to Portugal, or own property here, and are trying to work out how Portuguese insurance behaves when it is tested — what the law requires, what the standard wording quietly excludes, and where an internationally-minded household or business is exposed by a policy written for a domestic one.</p>
<p>The subjects follow that reality rather than mirroring our Portuguese section: health cover and residency requirements, homes on the Algarve coast and in Lisbon, holiday lets and Alojamento Local, valuables and collections, boats, cross-border company structures and professional liability. We name the applicable Portuguese legislation where it matters and we do not publish price rankings. If something here raises a question about your own policy, ask us — we are an insurance broker registered with the ASF under n.º 425591790/3 and the review costs nothing.</p>`;

// One original introduction per English category. These are written for the
// English reader rather than translated from the Portuguese equivalents, which
// address a different set of assumptions entirely.
const EN_CATEGORY_INTROS = {
  'health-insurance': `<p>Health cover is the first insurance question almost every English-speaking arrival in Portugal asks, and the one where the answer travels least well. The SNS exists and legal residents can register with it. What it does not do is behave like the private systems most newcomers are used to, either in waiting times or in choice of practitioner. Private cover here is bought alongside the SNS rather than instead of it, and working out which of the two you are actually relying on for a given episode of care is most of the decision.</p>
<p>The articles below deal with the parts that catch people out. Pre-existing conditions are underwritten case by case, and the answer differs by insurer rather than by market convention. Waiting periods run from the policy start date, not from the date you moved. Entry ages, renewal ages and how children are treated on a family policy all vary between companies. Visa applicants have a second problem on top of the first: the cover has to satisfy a consular requirement as well as a medical one, and a policy that is perfectly adequate clinically can still be refused as proof.</p>
<p>We also cover the situations that sit outside a domestic policy altogether — medical evacuation and repatriation, cover that has to keep working while you are abroad for months of the year, school-age children insured outside Portugal, and long-term care planning for residents who intend to stay. Where a requirement comes from legislation or from a visa rule we say which. We do not publish premium comparisons: the price of a health policy is a function of your age and your history, and an average figure describes nobody in particular.</p>`,

  'home-property': `<p>A Portuguese <em>multirriscos habitação</em> is not the same product as the household policy you left behind, and the differences are structural rather than cosmetic. The sum insured is meant to be the cost of rebuilding, not what the property would fetch. The policy the bank arranged with the mortgage protects the lender's interest first and yours second. Contents, liability and the boundary with the condominium's own policy are all handled differently here from the way they are in the UK, Ireland, the Netherlands or the United States.</p>
<p>This is the largest category on the English side because the housing itself is varied. A clifftop villa on the western Algarve, an apartment in a Lisbon building put up in the 1950s, a converted farmhouse in the interior and a golf resort townhouse are four different underwriting problems. So we write about earthquake cover, subsidence and coastal erosion, swimming pools and private jetties, guest annexes and staff quarters, solar panels and EV chargers, wine cellars, safes and alarm requirements, and the renovation of listed or heritage buildings — where the reinstatement obligation is not simply "as it was".</p>
<p>The other recurring theme is the gap between how a property is owned and how it is insured. Holding a house through a company, splitting a portfolio across two jurisdictions, buying before you have residency, leaving a second home empty for eight months of the year: each of these can quietly void or restrict a policy that was correct on the day it was written. Unoccupancy clauses in particular are the single most common reason we see a claim reduced. Where the answer depends on the specific wording, we say so rather than generalise.</p>`,

  'valuables-collections': `<p>Every household policy in Portugal covers valuables, and almost none of them covers them the way an owner of a real collection assumes. Cover is delivered through an overall limit for the class, a sublimit per item, and a set of conditions about where the item was kept and what security was in place. Items above the sublimit have to be specified individually. The distance between "insured" and "insured for what it is worth" is where most of the disappointment in this area lives.</p>
<p>The articles here work through that gap. Agreed value and market value are not the same basis and behave very differently on an appreciating asset — a watch, a classic car, a case of wine, a painting by an artist whose market has moved. Valuations have a shelf life, and insurers differ on how old a valuation they will accept and who they will accept it from. Safes, alarms and their certification are frequently a condition of cover rather than a discount on it, which means an unset alarm is a coverage question, not a discount question.</p>
<p>We also cover the situations where the object leaves the house: jewellery and watches worn while travelling, high-value bicycles and e-bikes ridden away from home, musical instruments carried to performances, and worldwide all-risks cover for personal possessions generally. And we cover arrival — shipping a collection to Portugal is a transit risk, a customs question and an insurance question at once, and the three are usually handled by three different parties who each assume one of the others has it.</p>`,

  'business-liability': `<p>Running a business in Portugal brings a set of insurance obligations that do not map neatly onto those of any other country, and a foreign-owned company usually meets them in the wrong order — incorporating first, discovering the compulsory covers second. Workers' compensation is the obvious one and it is compulsory from the first employee. Beyond it sit the covers required by a specific professional body, by a public tender, by a landlord, or by the contract with a single large client, none of which appear in any general list.</p>
<p>This category covers the liability lines a business actually gets asked for. Professional indemnity, where the trigger, the retroactive date and the run-off provision matter more than the limit. Directors' and officers' cover, including the exposure of a non-executive director sitting on a board in a country they do not live in. Cyber, which in practice means ransomware, business interruption and the notification obligations that follow a personal-data breach. Construction and works policies, where the parties insured change as the project moves between phases.</p>
<p>We also write about how the more unusual risks get placed. Not everything is quoted from a standard rating table: complementary therapy practices, family offices and fiduciary work, key-person cover for a business whose owner lives abroad, and distribution companies with stock in transit all need an underwriter who will look at the file rather than the postcode. Understanding which market a risk belongs in — and what an insurer needs to see before it will price it at all — is a large part of what an intermediary does.</p>`,

  motor: `<p>Motor insurance is compulsory in Portugal and the compulsory part is narrow: third-party liability, at the statutory minimum limits, for the vehicle rather than the driver. Everything an owner from another country tends to assume is included — own damage, glass, courtesy car, personal accident for the driver — is bought separately here. So is the treatment of a foreign no-claims history, which some insurers will recognise on documentary proof and others will not recognise at all.</p>
<p>The articles in this category start with the ordinary case: what an expatriate needs to insure a car here, what drives the cost, and what changes when the vehicle is matriculated in Portugal rather than driven on foreign plates. From there they move to the vehicles that a standard motor policy handles badly. A classic or collector car insured at market value is insured for an argument; agreed value exists precisely to avoid that. A car collection is better treated as one risk than as a stack of unrelated policies. High-value and performance cars raise questions about repair networks and parts sourcing that the premium alone does not answer.</p>
<p>Two exclusions come up often enough to deserve their own treatment. Track days and organised performance driving are excluded by essentially every private motor policy, and the exclusion is absolute rather than negotiable at the roadside. Carrying passengers for payment — TVDE work on Uber, Bolt or Free Now — is likewise excluded from a private policy and needs the risk declared from the outset. We also cover fleet policies, which usually become the better structure from around three vehicles.</p>`,

  'personal-family': `<p>The covers in this category are the ones nobody buys deliberately. They arrive attached to a household policy, or they do not arrive at all, and their absence is discovered at the point of claim. Family liability is the clearest example: it responds when a member of the household causes injury or damage to someone else, off the property as well as on it, and it is the cover most likely to be quietly missing from a policy assembled around the building.</p>
<p>Water damage deserves its own place here because it is the most frequent household claim in Portugal by a wide margin, and the one where the wording does the most work. Whether the escape of water is covered, whether the cost of finding the leak is covered, and whether damage to a neighbour's flat below is covered are three separate questions with three separate answers, and they differ between insurers rather than being fixed by law.</p>
<p>The rest of the category deals with the household as an employer and as a legal entity. Employing a nanny, a driver, a gardener or a housekeeper in Portugal makes you an employer with statutory obligations, workers' compensation among them, and informality about that is a liability rather than a saving. We also cover personal legal expenses, fraud and extortion cover, and what happens to jointly held policies during a separation or divorce — a moment at which cover routinely lapses because each party assumes the other is maintaining it.</p>`,

  'holiday-lets-hospitality': `<p>The moment a property earns rental income, the household policy covering it usually stops being the right policy. This is the single most common uninsured exposure we see among English-speaking owners in the Algarve: a home insured correctly as a home, then let for part of the year, with the letting never declared. Standard home cover contemplates the owner and their guests, not paying occupants and commercial use, and the insurer is entitled to say so after the event.</p>
<p>Registering the property under the Alojamento Local regime changes the obligations rather than removing them. The regime carries its own liability requirement, and the operator takes on responsibilities toward guests that a private owner does not have. This category sets out what the AL rules ask for, where the line falls between a second home you occasionally rent and a genuine short-let business, and how mixed personal and commercial use is handled when both are true in the same year.</p>
<p>The hospitality side covers the same ground at a larger scale. Bars, restaurants and small hotels have a claims profile of their own — public liability, food safety, employee injury, fire and business interruption — and the compulsory covers for tourism and hospitality businesses in Portugal are set out in legislation rather than left to the operator. We also cover the one-off risks the region generates: destination wedding cancellation, and prize indemnity for hole-in-one and similar promotional events on Algarve golf courses.</p>`,

  'moving-to-portugal': `<p>Insurance is rarely the first item on a relocation list, and it is regularly the one that blocks the others. You cannot register a vehicle without a NIF. You cannot complete on a property without cover in place at the moment of transfer. A visa application can require proof of health cover before you have an address to insure. The sequence matters, and getting it wrong costs weeks rather than money.</p>
<p>This category is about that sequence. It covers how to obtain a NIF as a non-resident, what fiscal representation actually is and when the law requires you to appoint someone, and what can and cannot be insured in the window between arriving and holding residency. That window is longer than most people plan for, and the answer differs by product: some policies can be issued on a NIF alone, others need proof of residence, and a few need neither.</p>
<p>Two of the articles here are written for specific groups because their questions genuinely differ. British residents have a post-Brexit position on healthcare entitlement and driving documentation that other EU-resident nationals do not. Americans arrive with assumptions from a health system that shares almost no structural features with the Portuguese one, and with reporting obligations that follow them abroad. We also cover something practical and rarely written about: how to run an insurance claim in Portugal when you do not speak Portuguese, and who is entitled to act for you.</p>`,

  marine: `<p>A boat in Portugal is regulated as a vessel first and insured as one second, and the two sets of rules interact. Registration, flag, the qualifications required of the person at the helm and the permitted use of the vessel all feed into what an underwriter will write and on what terms. An owner arriving with a boat already insured elsewhere frequently finds that the existing policy does not follow the vessel into Portuguese registration, or does not follow it into Portuguese waters for more than a fixed number of weeks.</p>
<p>This category covers the practical stages of that. Importing and registering a boat here, and what has to be in place before the paperwork will complete. The distinction between private use and charter, which is the single most important declaration on a yacht policy: carrying paying guests is a different risk, a different legal regime and, on most wordings, an outright exclusion unless it has been declared and rated.</p>
<p>We also cover the seasonal mechanics that generate claims. Lifting, lay-up and winter storage are periods when cover often changes shape — some risks fall away, others such as fire and theft ashore become more relevant, and the lifting operation itself can sit in a gap between the yard's liability and the owner's policy. Berthing in the Algarve marinas raises its own questions about third-party liability to neighbouring vessels and about what the marina's own cover does and does not extend to.</p>`,
};

const EN_CATEGORY_META = {
  'health-insurance': {
    title: 'Health Insurance in Portugal | Insights | Adler & Rochefort',
    description:
      'English-language analysis of health insurance in Portugal: the SNS alongside private cover, pre-existing conditions, waiting periods, visa proof and evacuation cover.',
  },
  'home-property': {
    title: 'Home & Property Insurance in Portugal | Insights | Adler & Rochefort',
    description:
      'Home insurance in Portugal for foreign owners: rebuild value, unoccupancy clauses, earthquake and coastal risk, pools and annexes, and property held through a company.',
  },
  'valuables-collections': {
    title: 'Valuables & Collections Insurance | Insights | Adler & Rochefort',
    description:
      'Insuring art, jewellery, watches, instruments, wine and collections in Portugal: sublimits, specified items, agreed value, valuations and worldwide cover.',
  },
  'business-liability': {
    title: 'Business & Liability Insurance in Portugal | Insights | Adler & Rochefort',
    description:
      'Compulsory business insurance in Portugal plus professional indemnity, D&O, cyber and construction cover — written for foreign-owned companies and their directors.',
  },
  motor: {
    title: 'Motor Insurance in Portugal | Insights | Adler & Rochefort',
    description:
      'Car insurance in Portugal for foreign residents: compulsory third-party liability, foreign no-claims history, classic and high-value cars, fleets, track days and TVDE.',
  },
  'personal-family': {
    title: 'Personal & Family Insurance in Portugal | Insights | Adler & Rochefort',
    description:
      'Family liability, water damage claims, employing domestic staff, legal expenses and fraud cover in Portugal — the household covers that are missed most often.',
  },
  'holiday-lets-hospitality': {
    title: 'Holiday Lets & Hospitality Insurance | Insights | Adler & Rochefort',
    description:
      'Alojamento Local and hospitality insurance in Portugal: why standard home cover fails on a let property, AL liability requirements and restaurant claims.',
  },
  'moving-to-portugal': {
    title: 'Moving to Portugal — Insurance | Insights | Adler & Rochefort',
    description:
      'Getting insured while moving to Portugal: NIF, fiscal representation, cover before residency, and how to run a claim when you do not speak Portuguese.',
  },
  marine: {
    title: 'Marine & Yacht Insurance in Portugal | Insights | Adler & Rochefort',
    description:
      'Boat and yacht insurance in Portugal: importing and registering a vessel, private use versus charter, winter lay-up and berthing in the Algarve marinas.',
  },
  'spain-health': {
    title: 'Health Insurance in Spain | Insights | Adler & Rochefort',
    description:
      'Private health insurance in Spain for expats: how it sits alongside the public system, pre-existing conditions, and what to check before a visa or residence application.',
  },
  'spain-property': {
    title: 'Property Insurance in Spain | Insights | Adler & Rochefort',
    description:
      'Property insurance in Spain for international owners: community buildings cover, non-resident ownership, second homes and renting out a property.',
  },
};

const enCategoryNav = (activeSlug) => {
  const chips = [
    `<a class="category-chip${activeSlug ? '' : ' active'}" href="/en/blog/">All<span class="category-chip-count">${enArticles.length}</span></a>`,
    ...EN_CATEGORIES.map((c) => {
      const n = enArticles.filter((a) => a.category === c.slug).length;
      return `<a class="category-chip${activeSlug === c.slug ? ' active' : ''}" href="/en/blog/category/${c.slug}/">${esc(c.short)}<span class="category-chip-count">${n}</span></a>`;
    }),
  ];
  return `<nav class="category-nav" aria-label="Categories">${chips.join('')}</nav>`;
};

const enPages = await buildListing({
  articles: enArticles,
  basePath: '/en/blog/',
  pageHref: (n) => `/en/blog/page/${n}/`,
  h1: 'Insights &mdash; <em>Insurance in Portugal, explained</em>',
  intro: EN_INTRO,
  meta: {
    title: 'Insights — Insurance in Portugal, explained | Adler & Rochefort',
    description:
      'English-language analysis of insurance in Portugal: health cover, homes and holiday lets, valuables, marine, business and liability — by an ASF-registered broker.',
  },
  crumbs: [
    { name: 'Home', url: '/en/' },
    { name: 'Insights', url: '/en/blog/' },
  ],
  nav: enCategoryNav(null),
  lang: 'en',
  cta: CTA_EN,
  collectionName: 'Insights',
});

for (const c of EN_CATEGORIES) {
  const items = enArticles.filter((a) => a.category === c.slug);
  const landing = c.landing
    ? `\n<p><strong>Looking for a quote rather than a read?</strong> See our <a href="${c.landing}">${esc(c.landingLabel)}</a> page.</p>`
    : '';
  await buildListing({
    articles: items,
    basePath: `/en/blog/category/${c.slug}/`,
    pageHref: (n) => `/en/blog/category/${c.slug}/page/${n}/`,
    h1: esc(c.title),
    intro: EN_CATEGORY_INTROS[c.slug] + landing,
    meta: EN_CATEGORY_META[c.slug],
    crumbs: [
      { name: 'Home', url: '/en/' },
      { name: 'Insights', url: '/en/blog/' },
      { name: c.title, url: `/en/blog/category/${c.slug}/` },
    ],
    nav: enCategoryNav(c.slug),
    lang: 'en',
    cta: CTA_EN,
    collectionName: c.title,
  });
}

// ---------------------------------------------------------------------------
// RSS
// ---------------------------------------------------------------------------

const rss = (items, { path, title, description, lang }) => {
  const latest = items.slice(0, 30);
  const pubDate = (d) => new Date(d).toUTCString();
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>${esc(title)}</title>
<link>${ORIGIN}${path.replace(/feed\.xml$/, '')}</link>
<description>${esc(description)}</description>
<language>${lang}</language>
<atom:link href="${ORIGIN}${path}" rel="self" type="application/rss+xml"/>
${latest
  .map(
    (a) => `<item>
<title>${esc(a.title)}</title>
<link>${ORIGIN}${a.url}</link>
<guid isPermaLink="true">${ORIGIN}${a.url}</guid>
<pubDate>${pubDate(a.published)}</pubDate>
<description>${esc(a.excerpt || a.description || '')}</description>
</item>`
  )
  .join('\n')}
</channel>
</rss>
`;
};

await mkdir(join(PUBLIC, 'blog'), { recursive: true });
await writeFile(
  join(PUBLIC, 'blog', 'feed.xml'),
  rss(ptArticles, {
    path: '/blog/feed.xml',
    title: 'Adler & Rochefort — Insights',
    description: 'Análises sobre seguros em Portugal.',
    lang: 'pt-PT',
  })
);
written.push('public/blog/feed.xml');

await mkdir(join(PUBLIC, 'en', 'blog'), { recursive: true });
await writeFile(
  join(PUBLIC, 'en', 'blog', 'feed.xml'),
  rss(enArticles, {
    path: '/en/blog/feed.xml',
    title: 'Adler & Rochefort — Insights',
    description: 'Insurance in Portugal, explained.',
    lang: 'en-GB',
  })
);
written.push('public/en/blog/feed.xml');

console.log(`PT index pages: ${ptPages}`);
console.log(`EN index pages: ${enPages}`);
console.log(`files written: ${written.length}`);
await writeFile(join(ROOT, 'data', 'generated-blog-pages.json'), JSON.stringify(written, null, 2) + '\n');
