#!/usr/bin/env python3
"""Polish leftover English on /de/*spanien* pages. No PT product pages touched."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
A = chr(38) + "amp;"
MDASH = chr(38) + "mdash;"

LANG_P = (
    "Diese Seite ist auf Deutsch. Intern ist unsere Arbeitssprache Englisch. "
    "Angebote, Erläuterungen zu den Bedingungen, Korrespondenz und Schadenabwicklung "
    "stellen wir Ihnen mit KI-Unterstützung auf Deutsch bereit — so klar, dass Sie den Unterschied kaum merken. "
    "Policen spanischer Versicherer werden gesetzlich auf Spanisch ausgestellt; wir sorgen dafür, "
    "dass Sie genau verstehen, was darin steht — auf Deutsch, schriftlich, bevor Sie unterschreiben."
)

def T():
    # (english, german) — longest first applied later
    return [
    # policy / trust / disclaimer
    ("Unsere Arbeitssprache ist Englisch " + MDASH + " the questions, the explanation of what a policy covers, and the correspondence. Where a Spanish insurer's policy wording is issued in Spanish, we make sure you understand what it says before you rely on it. All communication is in writing.",
     LANG_P),
    ("Korrespondenz auf Deutsch</strong> · Registered with Portugal’s ASF (no. 425591790/3) · A written answer, honestly, on what we can arrange",
     "Korrespondenz auf Deutsch</strong> · Bei der ASF Portugals registriert (Nr. 425591790/3) · Eine ehrliche schriftliche Antwort, was sich vermitteln lässt"),
    ("Korrespondenz auf Deutsch</strong> · Registered with Portugal’s ASF (no. 425591790/3) · A written answer on what can be arranged",
     "Korrespondenz auf Deutsch</strong> · Bei der ASF Portugals registriert (Nr. 425591790/3) · Eine schriftliche Antwort, was sich vermitteln lässt"),
    ("Adler " + A + " Rochefort is registered with Portugal's ASF, no. 425591790/3, and serves Spain on a cross-border basis —",
     "Adler " + A + " Rochefort ist bei der ASF Portugals registriert, Nr. 425591790/3, und in Spanien im Dienstleistungsverkehr tätig —"),
    ("English-speaking insurance broker, registered with Portugal's ASF. We help international residents and property owners in Portugal und Spanien work out what cover they need, and arrange it in English.",
     "Versicherungsmakler, bei der ASF Portugals registriert. Wir helfen internationalen Mandanten und Eigentümern in Portugal und Spanien, den passenden Schutz zu klären — Korrespondenz auf Deutsch."),
    ("By sending this form you agree to us using your details to prepare and discuss your quote, in line with our",
     "Mit dem Absenden erklären Sie sich einverstanden, dass wir Ihre Angaben zur Vorbereitung des Angebots verwenden, gemäß unserer"),
    ("We never sell your data. Adler " + A + " Rochefort is a trading name of Ownizo, Unipessoal Lda., registered with the ASF under no. 425591790/3.",
     "Wir verkaufen Ihre Daten nicht. Adler " + A + " Rochefort ist die Handelsmarke der Ownizo, Unipessoal Lda., bei der ASF unter Nr. 425591790/3 registriert."),
    ("No obligation to proceed. We may contact you for additional information before obtaining terms, and insurer acceptance and pricing remain subject to underwriting.",
     "Unverbindlich. Wir können vor der Einholung von Konditionen Rückfragen stellen; Annahme und Preis bleiben der Risikoprüfung des Versicherers vorbehalten."),
    ("General guidance only, for international clients considering or arranging insurance in Spain. What a policy actually covers, its excesses and its exclusions are set by the insurer and the wording of that specific policy — not by this page. Nothing here is legal, tax or immigration advice, and nothing here should be read as confirmation that a particular product is currently available: tell us your situation and we will confirm honestly what can be arranged.",
     "Nur allgemeine Orientierung für internationale Mandanten, die in Spanien Versicherung klären. Was eine Police tatsächlich deckt, Selbstbehalte und Ausschlüsse, steht im Wortlaut des Versicherers — nicht auf dieser Seite. Keine Rechts-, Steuer- oder Einwanderungsberatung. Nichts hier bestätigt, dass ein bestimmtes Produkt derzeit vermittelbar ist: schildern Sie uns Ihre Situation, wir sagen ehrlich, was sich einrichten lässt."),
    ("Wir bauen unsere Versichererbeziehungen in Spanien auf. Rather than guess at what we can place, we ask you a short set of questions about the property or the situation, then come back with a clear written answer — including telling you plainly if a particular case falls outside what we can currently arrange.",
     "Wir bauen unsere Versichererbeziehungen in Spanien auf. Statt zu raten, was sich platzieren lässt, stellen wir kurze Fragen zur Immobilie oder zur Lage und antworten schriftlich klar — einschließlich, wenn ein Fall derzeit außerhalb dessen liegt, was wir vermitteln können."),
    ("Already insured with us and need help with an existing claim?",
     "Schon bei uns versichert und brauchen Hilfe bei einem laufenden Schaden?"),
    ("this form is for new requests.",
     "dieses Formular ist für neue Anfragen."),
    ("See the full process:", "Den Ablauf im Überblick:"),
    ("how we work", "so arbeiten wir"),
    ("Claims support", "Schadenbegleitung"),
    # titles / meta
    (" | English-Speaking Service", ""),
    ("Insurance for expats, foreign residents and property owners in Spain, explained in English. Tell us your situation and we will confirm what can be arranged. Free written review.",
     "Versicherung für Expats, internationale Mandanten und Eigentümer in Spanien. Schildern Sie uns Ihre Situation — wir sagen, was sich vermitteln lässt. Kostenlose schriftliche Prüfung."),
    ("Helping international residents, expats and foreign property owners in Spain work out what insurance applies to their situation, in English, extending the service Adler & Rochefort has provided to expats in Portugal.",
     "Hilfe für internationale Mandanten, Expats und ausländische Eigentümer in Spanien, den passenden Schutz zu klären. Derselbe Service, den Adler & Rochefort seit Jahren in Portugal leistet."),
    ('"availableLanguage": [\n    "en"\n  ]', '"availableLanguage": [\n    "de",\n    "en"\n  ]'),
    ("Free written insurance review", "Kostenlose schriftliche Versicherungsprüfung"),
    ("Insurance guidance for expats and property owners in Spain",
     "Versicherungsorientierung für Expats und Eigentümer in Spanien"),
    ("Insurance intermediation — client qualification and referral",
     "Versicherungsvermittlung — Qualifizierung und Platzierung"),
    # form labels
    ("Full name *", "Vollständiger Name *"),
    ("Phone / WhatsApp *", "Telefon / WhatsApp *"),
    ("Where do you currently live? *", "Wo leben Sie derzeit? *"),
    ("Where in Spain will the car be kept? *", "Wo in Spanien steht das Fahrzeug? *"),
    ("Where in Spain? *", "Wo in Spanien? *"),
    ("Where is the property? (town/region, Spain) *", "Wo liegt die Immobilie? (Ort/Region, Spanien) *"),
    ("Where is the property? *", "Wo liegt die Immobilie? *"),
    ("Vehicle registration status *", "Zulassungsstatus *"),
    ("Vehicle’s country of registration", "Zulassungsland des Fahrzeugs"),
    ("Country that issued your driving licence *", "Ausstellungsland des Führerscheins *"),
    ("Year you first held a full licence", "Jahr der ersten vollen Fahrerlaubnis"),
    ("Claims history", "Schadenverlauf"),
    ("Intended use", "Nutzung"),
    ("Anything we should know?", "Was sollten wir noch wissen?"),
    ("Your situation *", "Ihre Situation *"),
    ("Your situation", "Ihre Situation"),
    ("How is the property used?", "Wie wird die Immobilie genutzt?"),
    ("How is the property let? *", "Wie wird vermietet? *"),
    ("Cover you are looking for", "Gewünschte Deckung"),
    ("Mortgage status *", "Status der Hypothek *"),
    ("Borrower type", "Art der Kreditnehmer"),
    ("Approximate loan amount", "Ungefähre Kreditsumme"),
    ("Residency status", "Aufenthaltsstatus"),
    ("Number of people to insure *", "Anzahl der zu versichernden Personen *"),
    ("Age(s) of those to be insured *", "Alter der zu versichernden Personen *"),
    ("Type of cover needed", "Art der gewünschten Deckung"),
    ("Is this for a visa or residence application?", "Geht es um Visum oder Aufenthalt?"),
    ("Existing health insurance, and any notes", "Bestehende Krankenversicherung und Anmerkungen"),
    ("Current country of residence *", "Derzeitiges Wohnsitzland *"),
    ("Country of residence *", "Wohnsitzland *"),
    ("Age range *", "Altersgruppe *"),
    ("Number of dependants", "Anzahl der Angehörigen"),
    ("Approximate cover required", "Ungefähre Versicherungssumme"),
    ("Do you have a mortgage in Spain?", "Haben Sie eine Hypothek in Spanien?"),
    ("Do you already have life cover elsewhere?", "Besteht bereits Lebensversicherung im Ausland?"),
    ("Main objective", "Hauptziel"),
    ("Smoker? (optional)", "Raucher? (optional)"),
    ("Immobilie ownership *", "Immobilienbesitz *"),
    ("Number of properties (Spain)", "Anzahl der Immobilien (Spanien)"),
    ("Fahrzeuge to consider", "Fahrzeuge"),
    ("Which risks would you like reviewed?", "Welche Risiken sollen geprüft werden?"),
    ("Preferred contact method", "Bevorzugter Kontaktweg"),
    ("Other risks or notes", "Weitere Risiken oder Anmerkungen"),
    ("Furnished?", "Möbliert?"),
    ("Current insurance", "Aktuelle Versicherung"),
    ("What do you need help with? *", "Wobei brauchen Sie Hilfe? *"),
    ("Tell us about the property or situation", "Schildern Sie Immobilie oder Situation"),
    ("Select one", "Bitte wählen"),
    # options
    ("Spanish-registered already", "Bereits spanisch zugelassen"),
    ("Foreign-registered, import in process", "Ausländische Zulassung, Import läuft"),
    ("Foreign-registered, not yet started", "Ausländische Zulassung, Import noch nicht begonnen"),
    ("Buying a car in Spain, not chosen yet", "Kauf in Spanien, Fahrzeug noch nicht gewählt"),
    ("Claim-free, letter from previous insurer available", "Schadenfrei, Bestätigung des Vorversicherers vorhanden"),
    ("Claim-free, no letter yet", "Schadenfrei, noch ohne Bestätigung"),
    ("One or more claims in the last 5 years", "Ein oder mehrere Schäden in den letzten 5 Jahren"),
    ("Already have a Spanish claims record", "Bereits spanischer Schadenverlauf"),
    ("Newly licensed / no history yet", "Frisch führerschein / noch ohne Verlauf"),
    ("Villa / detached house", "Villa / freistehendes Haus"),
    ("Resident owner", "Resident, selbst genutzt"),
    ("Non-resident owner", "Nicht-resident Eigentümer"),
    ("Buying — not completed yet", "Kauf — noch nicht abgeschlossen"),
    ("Renting (contents only)", "Miete (nur Hausrat)"),
    ("Permanent residence", "Hauptwohnsitz"),
    ("Holiday home / used part of the year", "Zweitwohnsitz / saisonal"),
    ("Currently empty", "Derzeit leerstehend"),
    ("Let out to tenants or guests", "An Mieter oder Gäste vermietet"),
    ("Unsicher — advise me", "Unsicher — beraten Sie mich"),
    ("Buildings only", "Nur Gebäude"),
    ("Contents only", "Nur Hausrat"),
    ("Buildings and contents", "Gebäude und Hausrat"),
    ("Applying now", "Antrag läuft"),
    ("Mortgage approved, not yet completed", "Hypothek zugesagt, noch nicht abgeschlossen"),
    ("Already have a Spanish mortgage", "Bereits spanische Hypothek"),
    ("Considering a purchase", "Kauf in Überlegung"),
    ("Single borrower", "Alleiniger Kreditnehmer"),
    ("Joint borrowers", "Mitantragsteller"),
    ("Unsicher yet", "Noch unsicher"),
    ("Resident in Spain", "Resident in Spanien"),
    ("Non-resident", "Nicht-resident"),
    ("Becoming resident soon", "Bald Resident"),
    ("1 (just me)", "1 (nur ich)"),
    ("5 or more", "5 oder mehr"),
    ("Already resident in Spain", "Bereits Resident in Spanien"),
    ("Moving to Spain soon", "Bald Umzug nach Spanien"),
    ("Considering a move, no date yet", "Umzug in Überlegung, noch kein Termin"),
    ("Individual with copayments (lower cost)", "Einzelperson mit Selbstbeteiligung (günstiger)"),
    ("Individual without copayments", "Einzelperson ohne Selbstbeteiligung"),
    ("Under 30", "Unter 30"),
    ("60 or over", "60 oder älter"),
    ("Not yet, but considering one", "Noch nicht, aber in Überlegung"),
    ("Family protection", "Familienschutz"),
    ("Business/partnership obligation", "Betriebliche / Gesellschafterpflicht"),
    ("Reviewing existing cover", "Bestehenden Schutz prüfen"),
    ("Prefer not to say", "Keine Angabe"),
    ("Non-smoker", "Nichtraucher"),
    ("One property in Spain", "Eine Immobilie in Spanien"),
    ("More than one property in Spain", "Mehrere Immobilien in Spanien"),
    ("Immobilie in Spain and elsewhere", "Immobilie in Spanien und anderswo"),
    ("Not yet, planning to buy", "Noch nicht, Kauf geplant"),
    ("Long-term rental", "Langzeitvermietung"),
    ("Short-term / holiday letting", "Kurzzeit / Ferienvermietung"),
    ("A mix of both", "Beides gemischt"),
    ("Not let yet — planning to", "Noch nicht vermietet — geplant"),
    ("Partly furnished", "Teilmöbliert"),
    ("I live in Spain", "Ich lebe in Spanien"),
    ("I live outside Spain", "Ich lebe außerhalb Spaniens"),
    ("Managed by a local agent on my behalf", "Verwaltet durch eine lokale Agentur"),
    ("No policy yet", "Noch keine Police"),
    ("Standard home policy (may need to change)", "Standard-Hauspolice (vermutlich anpassen)"),
    ("Already have landlord cover, renewal coming up", "Bereits Vermieterdeckung, Verlängerung steht an"),
    ("Unsicher what I have", "Unsicher, was ich habe"),
    ("Home insurance for a property in Spain", "Hausversicherung für eine Immobilie in Spanien"),
    ("Landlord / rental property insurance", "Vermieter- / Mietobjektversicherung"),
    ("Private client review — several risks at once", "Private-Client-Prüfung — mehrere Risiken zugleich"),
    ("Reviewing a policy I already have", "Bestehende Police prüfen"),
    ("Unsicher — help me work it out", "Unsicher — helfen Sie mir, das zu klären"),
    ("Something else (tell us below)", "Sonstiges (unten beschreiben)"),
    ("I own property in Spain and live there", "Ich besitze eine Immobilie in Spanien und lebe dort"),
    ("I own property in Spain but live elsewhere", "Ich besitze eine Immobilie in Spanien, lebe aber anderswo"),
    ("I am buying property in Spain", "Ich kaufe eine Immobilie in Spanien"),
    ("I am renting in Spain", "Ich miete in Spanien"),
    ("I do not have a property in Spain yet", "Ich habe noch keine Immobilie in Spanien"),
    ("e.g. United Kingdom", "z. B. Deutschland"),
    ("e.g. Alicante, Costa Blanca", "z. B. Alicante, Costa Blanca"),
    ("Jane Smith", "Max Mustermann"),
    ("you@example.com", "ihr.name@email.de"),
    # leftover H2s
    ("Importing and registering a vehicle", "Import und Zulassung eines Fahrzeugs"),
    ("What affects the price", "Was den Preis bestimmt"),
    ("What we typically need", "Was wir in der Regel brauchen"),
    ("If something happens", "Wenn etwas passiert"),
    ("Get a car insurance quote", "Autoversicherung anfragen"),
    ("Get a home insurance quote", "Hausversicherung anfragen"),
    ("Get a health insurance quote", "Krankenversicherung anfragen"),
    ("Get a life insurance review", "Lebensversicherung prüfen lassen"),
    ("Get a Autoversicherung Quote", "Autoversicherung anfragen"),
    ("Get a Krankenversicherung Quote", "Krankenversicherung anfragen"),
    ("Get a home insurance quote", "Hausversicherung anfragen"),
    ("Request a mortgage protection review", "Hypothekenschutz prüfen lassen"),
    ("Request a private client review", "Private-Client-Prüfung anfragen"),
    ("Policy ownership and beneficiaries, at a high level", "Versicherungsnehmer und Begünstigte, im Überblick"),
    ("Waiting periods", "Wartezeiten"),
    ("Visas, residence and proof of cover", "Visum, Aufenthalt und Nachweis der Deckung"),
    ("Domestic Spanish cover or wider international cover?", "Spanische Inlandsdeckung oder weitere internationale Deckung?"),
    ("Families", "Familien"),
    ("Retirees", "Rentner"),
    ("How to get a quote", "So kommen Sie zu einem Angebot"),
    ("If you already hold life cover from another country", "Wenn Sie bereits Lebensversicherung aus einem anderen Land haben"),
    ("How to request a review", "So fordern Sie eine Prüfung an"),
    ("Landlord and investment property", "Vermietung und Anlageimmobilien"),
    ("International client service", "Service für internationale Mandanten"),
    ("Health insurance in Spain", "Krankenversicherung in Spanien"),
    ("Buying or renting as you arrive", "Kaufen oder mieten bei der Ankunft"),
    ("Already living in Spain", "Bereits in Spanien lebend"),
    ("Buying property in Spain", "Immobilie in Spanien kaufen"),
    ("Renting out property in Spain", "Immobilie in Spanien vermieten"),
    ("Non-resident property owners", "Nicht-residente Eigentümer"),
    ("Unsicher what insurance you need?", "Unsicher, welche Versicherung Sie brauchen?"),
    ("Why Adler " + A + " Rochefort", "Warum Adler " + A + " Rochefort"),
    ("Related reading", "Verwandte Themen"),
    ("Guides worth reading first", "Verwandte Themen"),
    ("Related cover", "Passende weitere Deckung"),
    ("Spain · Car insurance", "Spanien · Autoversicherung"),
    ("Spain · Home insurance", "Spanien · Hausversicherung"),
    ("Spain · Health insurance", "Spanien · Krankenversicherung"),
    ("Spain · Life insurance", "Spanien · Lebensversicherung"),
    ("Spain · Landlord insurance", "Spanien · Vermieterversicherung"),
    ("Spain · Mortgage protection", "Spanien · Hypothekenschutz"),
    ("Spain · Private clients", "Spanien · Private Clients"),
    ("Insurance for expats in Spain", "Versicherungen für Expats in Spanien"),
    ("Get a quote", "Angebot anfragen"),
    ("Living in Spain? You may also need:", "Sie leben in Spanien? Häufig dazu:"),
    ("Looking for Portugal?", "Suchen Sie Portugal?"),
    ("Looking for Portugal instead?", "Lieber Portugal?"),
    ("Insurance for expats", "Versicherungen für Expats"),
    ("health insurance in Spain", "Krankenversicherung in Spanien"),
    ("home insurance in Spain", "Hausversicherung in Spanien"),
    ("car insurance in Spain", "Autoversicherung in Spanien"),
    ("life insurance in Spain", "Lebensversicherung in Spanien"),
    ("landlord insurance in Spain", "Vermieterversicherung in Spanien"),
    ("mortgage protection in Spain", "Hypothekenschutz in Spanien"),
    ("private client insurance in Spain", "Private-Client-Versicherung in Spanien"),
    ("This is covered in full on", "Ausführlich auf"),
    ("in English", "auf Deutsch"),
    ]
    # Note: "in English" as global replace is risky in body explaining "treatment in English"
    # I'll apply it carefully later, not as a blanket last item.
    # Remove last item from this list - I'll handle separately.


def strip_blog_cards(html: str) -> str:
    html = re.sub(
        r'\s*<div class="lp-card">\s*<h2>Verwandte Themen</h2>[\s\S]*?</div>',
        "",
        html,
        count=2,
    )
    html = re.sub(
        r'\s*<div class="lp-card">\s*<h2>Related reading</h2>[\s\S]*?</div>',
        "",
        html,
        count=2,
    )
    html = re.sub(
        r'\s*<div class="lp-card">\s*<h2>Guides worth reading first</h2>[\s\S]*?</div>',
        "",
        html,
        count=2,
    )
    # related reading as lp-sections block that only contains blog lists
    html = re.sub(
        r'<section class="lp-sections">\s*<div class="lp-sections-inner">\s*<div class="lp-card">\s*<h2>Verwandte Themen</h2>[\s\S]*?</section>',
        "",
        html,
        count=1,
    )
    return html


BLOG_TO_CLUSTER = [
    ("/en/blog/second-home-insurance-spain/", "/de/hausversicherung-spanien/"),
    ("/en/blog/insurance-buying-property-spain/", "/de/hausversicherung-spanien/"),
    ("/en/blog/non-resident-property-insurance-spain/", "/de/hausversicherung-spanien/"),
    ("/en/blog/family-insurance-spain/", "/de/versicherung-spanien/"),
    ("/en/blog/community-insurance-apartment-owners-spain/", "/de/hausversicherung-spanien/"),
    ("/en/blog/high-value-home-insurance-spain/", "/de/private-clients-spanien/"),
    ("/en/blog/renting-out-property-in-spain/", "/de/vermieterversicherung-spanien/"),
    ("/en/blog/car-insurance-spain-expats/", "/de/autoversicherung-spanien/"),
    ("/en/blog/foreign-driving-licence-car-insurance-spain/", "/de/autoversicherung-spanien/"),
    ("/en/blog/foreign-registered-car-insurance-spain/", "/de/autoversicherung-spanien/"),
    ("/en/blog/no-claims-history-car-insurance-spain/", "/de/autoversicherung-spanien/"),
    ("/en/blog/importing-car-to-spain-insurance/", "/de/autoversicherung-spanien/"),
    ("/en/blog/health-insurance-moving-to-spain/", "/de/krankenversicherung-spanien/"),
    ("/en/blog/private-health-insurance-spain-expats/", "/de/krankenversicherung-spanien/"),
    ("/en/blog/spain-health-insurance-visa-residency/", "/de/krankenversicherung-spanien/"),
    ("/en/blog/life-insurance-spain-expats/", "/de/lebensversicherung-spanien/"),
    ("/en/blog/mortgage-life-insurance-spain/", "/de/hypothekenschutz-spanien/"),
    ("/en/blog/insurance-review-expats-spain/", "/de/versicherung-spanien/"),
    ("/en/blog/insurance-portugal-spain-international-residents/", "/de/versicherung-spanien/"),
    ("/en/blog/category/spain-car/", "/de/autoversicherung-spanien/"),
    ("/en/blog/category/spain-health/", "/de/krankenversicherung-spanien/"),
    ("/en/blog/category/spain-life/", "/de/lebensversicherung-spanien/"),
    ("/en/blog/category/spain-private-clients/", "/de/private-clients-spanien/"),
    ("/en/blog/category/spain-property/", "/de/hausversicherung-spanien/"),
]


# Long unique body paragraphs — hub + shared product copy
BODY = None  # filled below with AMP-safe strings


def body_pairs():
    return [
    ("Considering, moving to, or already living in Spain? We help international clients work out what insurance actually applies to their situation, and arrange it in English — from Portugal, extending the same service we have provided for expats here for several years.",
     "Überlegen Sie den Schritt, ziehen Sie um, oder leben Sie bereits in Spanien? Wir klären mit internationalen Mandanten, welcher Schutz tatsächlich zur Lage passt — vom Sitz in Portugal aus, derselbe Service wie seit Jahren für Expats hier."),
    ("Spanish insurance is not written for someone reading it for the first time from abroad. The policy wording is Spanish, the assumptions behind it are Spanish, and the questions an insurer asks — how the property is used, who holds the title, whether you are resident — have answers that are straightforward if you grew up with the system and much less obvious if you did not.",
     "Spanische Versicherungen sind nicht für jemanden geschrieben, der sie zum ersten Mal aus dem Ausland liest. Der Wortlaut ist spanisch, die Annahmen sind spanisch, und die Fragen des Versicherers — Nutzung, Eigentum, Residenz — sind einfach, wenn man mit dem System aufgewachsen ist, und deutlich weniger offensichtlich, wenn nicht."),
    ("That gap rarely shows up as a dramatic failure. It shows up as a policy that quietly does not match the situation: a home insured as a permanent residence when it stands empty for most of the year, a rental property covered under a standard homeowner policy that was never designed for tenants, cover bought quickly to satisfy a mortgage lender and then never looked at again. Those gaps tend to surface at a claim, which is the worst moment to discover them.",
     "Die Lücke zeigt sich selten als großer Knall. Sie zeigt sich als Police, die leise nicht zur Lage passt: ein Haus als Hauptwohnsitz versichert, das die meiste Zeit leer steht; ein Mietobjekt unter einer Eigentümerpolice, die nie für Mieter gedacht war; Deckung, die schnell für die Bank gekauft und nie wieder angefasst wurde. Das kommt im Schadenfall zum Vorschein — der schlechteste Moment."),
    ("This page exists to answer one question first:",
     "Diese Seite beantwortet zuerst eine Frage:"),
    ("what insurance actually applies to your situation in Spain, and what should you sort out in what order?",
     "welche Versicherung zu Ihrer Lage in Spanien wirklich passt — und in welcher Reihenfolge Sie das klären sollten?"),
    ("Once that is clear, the product pages below cover the detail, each with its own form.",
     "Ist das klar, liefern die Produktseiten darunter das Detail — jede mit eigenem Formular."),
    ("The products we can currently discuss properly for Spain are set out below. If your situation is different — a business — say so in the form at the bottom of this page and we will tell you honestly whether it is something we can help with yet.",
     "Die Sparten, die wir für Spanien derzeit seriös besprechen können, stehen unten. Ist Ihre Lage anders — ein Betrieb —, schreiben Sie das ins Formular am Ende. Wir sagen ehrlich, ob wir schon helfen können."),
    ("Private medical cover for individuals and families moving to, or already living in, Spain.",
     "Private Krankenversicherung für Einzelpersonen und Familien, die nach Spanien ziehen oder bereits dort leben."),
    ("Permanent residences, holiday homes and second homes — resident or non-resident owner.",
     "Hauptwohnsitz, Ferienhaus und Zweitwohnsitz — resident oder nicht-resident."),
    ("Immobilie you let out in Spain, long-term or holiday rental, managed locally or remotely.",
     "Immobilie, die Sie in Spanien vermieten — Langzeit oder Ferien, lokal oder aus der Ferne verwaltet."),
    ("For expats, international residents and foreign drivers with a vehicle in Spain.",
     "Für Expats, internationale Mandanten und Fahrer mit einem Fahrzeug in Spanien."),
    ("Family and mortgage protection for international residents, and a review of cover you already hold elsewhere.",
     "Familien- und Hypothekenschutz für internationale Mandanten, und Prüfung von Deckung, die Sie bereits anderswo haben."),
    ("A coordinated review across several risks at once — for households with more than one property, vehicle or jurisdiction to think about.",
     "Eine abgestimmte Prüfung mehrerer Risiken zugleich — für Haushalte mit mehr als einer Immobilie, einem Fahrzeug oder mehreren Rechtsräumen."),
    ("Different situations point to different insurance — say which is closest to yours and start there. This is a routing guide, not a recommendation engine, and not immigration or relocation advice: we are an insurance intermediary, not a relocation service, and the questions below are all about cover, not about visas, paperwork or the move itself.",
     "Unterschiedliche Lagen führen zu unterschiedlicher Versicherung — wählen Sie, was am nächsten kommt. Das ist eine Orientierung, keine Empfehlungsmaschine und keine Einwanderungsberatung: wir sind Versicherungsmakler, kein Relocation-Service. Die Fragen unten betreffen den Schutz, nicht Visum, Papierkram oder den Umzug selbst."),
    ("Already resident or settled in? Health, car and home are usually the first three worth checking. See",
     "Bereits Resident oder sesshaft? Kranken, Auto und Haus sind meist die ersten drei, die sich zu prüfen lohnen. Siehe"),
    ("What actually comes up during a purchase — buildings, mortgage protection, and whether you plan to let it out. See",
     "Was beim Kauf tatsächlich auftaucht — Gebäude, Hypothekenschutz, und ob Sie vermieten wollen. Siehe"),
    ("insurance to consider when buying property in Spain", "Versicherung beim Immobilienkauf in Spanien"),
    ("A property you live in yourself, resident or not. See",
     "Eine Immobilie, in der Sie selbst wohnen, resident oder nicht. Siehe"),
    ("Used for part of the year rather than lived in full-time — insurers price that differently. See",
     "Einen Teil des Jahres genutzt, nicht durchgehend bewohnt — Versicherer bepreisen das anders. Siehe"),
    ("second-home insurance in Spain", "Zweitwohnsitzversicherung in Spanien"),
    ("Long-term or holiday letting both change what needs to be covered. See",
     "Langzeit- wie Ferienvermietung ändern, was gedeckt sein muss. Siehe"),
    ("Nicht-resident Eigentümerhip is normal and normally insurable. See",
     "Nicht-resident Eigentum ist üblich und in der Regel versicherbar. Siehe"),
    ("property insurance in Spain for non-resident owners", "Immobilienversicherung in Spanien für nicht-residente Eigentümer"),
    ("Individual or family cover, resident or arriving soon. See",
     "Einzel- oder Familienpolice, resident oder bald ankommend. Siehe"),
    ("Bringing one, buying one, or already driving in Spain. See",
     "Mitbringen, kaufen oder bereits in Spanien fahren. Siehe"),
    ("What a lender actually requires versus what it simply offers. See",
     "Was die Bank wirklich verlangt — und was sie nur anbietet. Siehe"),
    ("How health, home, car and life tend to connect for a family, and which of them actually apply to yours. See",
     "Wie Kranken, Haus, Auto und Leben bei einer Familie zusammenhängen — und was davon auf Ihre zutrifft. Siehe"),
    ("insurance for families living in Spain", "Versicherung für Familien in Spanien"),
    ("Several properties, vehicles or policies worth reviewing together, once. See",
     "Mehrere Immobilien, Fahrzeuge oder Policen, die sich einmal gemeinsam prüfen lassen. Siehe"),
    ("Unsicher where you fit?", "Unsicher, wo Sie hingehören?"),
    ("instead and tell us what you need help with — one form, one broker.",
     "und sagen Sie uns, wobei Sie Hilfe brauchen — ein Formular, ein Makler."),
    ("Life insurance tends to come up for the same handful of reasons — dependants, a mortgage, a business partner, or simply a foreign policy that needs reviewing now that you live in Spain. What sum insured makes sense, and what a specific policy actually covers, depends on the individual and the insurer, not on a generic rule.",
     "Lebensversicherung kommt meist aus denselben Gründen: Angehörige, Hypothek, Geschäftspartner, oder eine ausländische Police, die jetzt, da Sie in Spanien leben, geprüft werden muss. Welche Summe Sinn ergibt und was eine konkrete Police deckt, hängt von Person und Versicherer ab — nicht von einer Pauschalregel."),
    ("including what to do about cover you already hold from another country, and how mortgage protection fits in — see",
     "einschließlich, was mit Deckung aus einem anderen Land zu tun ist, und wie Hypothekenschutz dazugehört — siehe"),
    ("Some households simply have more moving parts — a property or two, a car, health cover for the family, some landlord exposure — arranged with different insurers at different times, in different languages. Reviewing all of it together, once, tends to surface gaps and duplication that nobody notices when each policy is looked at on its own.",
     "Manche Haushalte haben einfach mehr bewegliche Teile — eine oder zwei Immobilien, ein Auto, Kranken für die Familie, etwas Vermietung — bei verschiedenen Versicherern, zu verschiedenen Zeiten, in verschiedenen Sprachen. Einmal gemeinsam geprüft, kommen Lücken und Doppelungen zum Vorschein, die niemand sieht, wenn jede Police einzeln betrachtet wird."),
    ("one coordinated review, not a luxury-branded product line.",
     "eine abgestimmte Prüfung, keine Luxus-Produktlinie."),
    ("Whether you are bringing a car with you, buying one after you arrive, or already driving on a Spanish-registered vehicle, motor cover in Spain has to match the vehicle’s actual situation — where it is registered, who holds the driving licence, and how it is used. Third-party liability is compulsory by law for every vehicle in Spain; what sits above that is a matter of insurer, plan and the profile of the driver.",
     "Ob Sie ein Auto mitbringen, nach der Ankunft kaufen oder bereits ein spanisch zugelassenes fahren: die Kfz-Deckung muss zur tatsächlichen Lage passen — Zulassung, Führerschein, Nutzung. Haftpflicht ist in Spanien für jedes Fahrzeug gesetzlich Pflicht; was darüber liegt, ist Sache von Versicherer, Tarif und Fahrerprofil."),
    ("including foreign driving licences, foreign-registered vehicles, and what actually affects the price.",
     "einschließlich ausländischer Führerscheine, ausländisch zugelassener Fahrzeuge und was den Preis wirklich bewegt."),
    ("Private health insurance is one of the most common questions we hear from people moving to Spain — often because a visa or residence application asks for proof of cover, and often simply because private access sits alongside the public system rather than replacing it. What a plan actually includes, and what it costs, depends on the insurer, the plan and the people being covered.",
     "Private Krankenversicherung ist eine der häufigsten Fragen beim Umzug nach Spanien — oft, weil Visum oder Aufenthalt einen Nachweis verlangen, oft weil der Privatweg neben dem öffentlichen System liegt, statt ihn zu ersetzen. Was ein Tarif enthält und was er kostet, hängt von Versicherer, Tarif und den versicherten Personen ab."),
    ("including what typically decides cover, pre-existing conditions, and what to check before a visa or residence application.",
     "einschließlich, was die Deckung typischerweise bestimmt, Vorerkrankungen, und was vor Visum oder Aufenthalt zu prüfen ist."),
    ("People moving to Spain usually have one insurance question that is urgent — the property they are buying or renting — and several others that can wait a few weeks. We are not an immigration or tax adviser and this page is not visa guidance; what we can do is help you sequence the insurance side sensibly once the property and the timeline are clear.",
     "Wer nach Spanien zieht, hat meist eine dringende Versicherungsfrage — die Immobilie, die gekauft oder gemietet wird — und mehrere, die ein paar Wochen warten können. Wir sind keine Einwanderungs- oder Steuerberater, diese Seite ist keine Visa-Hilfe. Was wir können: die Versicherungsseite sinnvoll reihen, sobald Immobilie und Zeitplan klar sind."),
    ("A mortgage lender in Spain will typically expect buildings cover in place before completion. Exactly what is required varies by lender and by property — tell us the timeline and we will tell you what to have ready.",
     "Eine spanische Bank erwartet in der Regel Gebäudeversicherung vor dem Abschluss. Was genau verlangt wird, hängt von Bank und Immobilie ab — nennen Sie den Zeitplan, wir sagen, was bereitliegen muss."),
    ("A landlord’s own building insurance does not cover your belongings. If you are renting, contents cover for what you actually own is a separate, usually inexpensive, item worth arranging early.",
     "Die Gebäudeversicherung des Vermieters deckt Ihr Hab und Gut nicht. Wenn Sie mieten, ist Hausrat für das, was Ihnen gehört, ein eigener, meist günstiger Posten — früh sinnvoll."),
    ("A home that is unoccupied for an extended period is a different risk to underwrite than one lived in daily — insurers ask about this directly, and answering it accurately matters more than it looks.",
     "Ein länger leerstehendes Haus ist ein anderes Risiko als eines, in dem täglich gewohnt wird — Versicherer fragen das direkt, und eine genaue Antwort zählt mehr, als es wirkt."),
    ("Nicht-resident Eigentümerhip is common and normally insurable, but the paperwork an insurer wants and the postal address they use for correspondence both need to be right from the start.",
     "Nicht-resident Eigentum ist üblich und in der Regel versicherbar. Unterlagen und die Postadresse für die Korrespondenz müssen von Anfang an stimmen."),
    ("If you already have a Spanish home insurance policy, the most useful thing we can usually do is look at what you have. Sums insured that were never updated, a policy written in Spanish that nobody has fully explained, cover bought quickly on moving day and never revisited — these come up constantly, and a review costs you nothing to find out.",
     "Haben Sie bereits eine spanische Hauspolice, ist das Nützlichste meist, sie anzusehen. Nie aktualisierte Summen, ein spanischer Wortlaut, den niemand erklärt hat, Deckung vom Umzugstag, nie wieder angefasst — das kommt ständig vor. Eine Prüfung kostet Sie nichts."),
    ("Send us your current policy and we will tell you plainly what it covers, in English, and whether it still matches how you actually use the property.",
     "Schicken Sie uns Ihre aktuelle Police. Wir sagen klar, was sie deckt — auf Deutsch — und ob sie noch zur tatsächlichen Nutzung passt."),
    ("Whether the property is a full-time home, a holiday house you will use for part of the year, or an investment, the starting point is the same: buildings cover in place from the date you take on the risk, and a clear answer on what contents cover you actually need. The detail — sums insured, unoccupancy terms, whether the property sits within a community of owners with its own building policy — is what the form on the next page walks through.",
     "Ob Hauptwohnsitz, Ferienhaus oder Anlage: der Ausgangspunkt ist derselbe. Gebäudeversicherung ab dem Tag, an dem Sie das Risiko übernehmen, und eine klare Antwort, welchen Hausrat Sie wirklich brauchen. Das Detail — Summen, Leerstandsbedingungen, ob die Immobilie in einer Comunidad mit eigener Gebäudepolice liegt — führt das Formular der nächsten Seite durch."),
    ("A standard home policy is written around an owner living in the property. The moment someone else is paying to stay there — a long-term tenant or a short holiday let — the risk changes, and a homeowner policy is usually the wrong contract for it. This applies whether you manage the property yourself or through a local agency.",
     "Eine Standard-Hauspolice ist für den selbstnutzenden Eigentümer geschrieben. Sobald jemand anderes dafür zahlt, dort zu wohnen — Langzeitmieter oder Kurzzeitgast — ändert sich das Risiko, und die Eigentümerpolice ist meist der falsche Vertrag. Das gilt, ob Sie selbst verwalten oder eine lokale Agentur."),
    ("A large share of the international owners we hear from do not live in Spain at all — in the UK, elsewhere in Europe, or further afield — and manage a Spanish property from a distance, using it seasonally, renting it out, or leaving it with a keyholder. None of that is unusual, and none of it should mean guessing at cover in a language you do not read fluently.",
     "Ein großer Teil der internationalen Eigentümer, die uns schreiben, lebt gar nicht in Spanien — in Deutschland, anderswo in Europa oder weiter weg — und führt die Immobilie aus der Ferne: saisonal, vermietet, oder mit einem Schlüsselhalter. Nichts davon ist ungewöhnlich, und nichts davon sollte heißen, den Schutz in einer Sprache zu raten, die Sie nicht flüssig lesen."),
    ("Correspondence, claims and the policy explanation all happen in English, whichever country the property sits in.",
     "Korrespondenz, Schäden und die Erläuterung der Police laufen auf Deutsch — unabhängig davon, in welchem Land die Immobilie steht."),
    ("Same principle — the working language is English, and we ask about your own residency and tax position only where it genuinely affects the cover.",
     "Dasselbe Prinzip — die Korrespondenz mit Ihnen läuft schriftlich auf Deutsch. Residenz und Steuerlage fragen wir nur, wo sie die Deckung wirklich berühren."),
    ("Time zones and distance make a written comparison more useful than a phone call; that is how we normally work in any case.",
     "Zeitzonen und Distanz machen einen schriftlichen Vergleich nützlicher als einen Anruf; so arbeiten wir ohnehin meist."),
    ("Both change the risk an insurer is actually being asked to price. Tell us the pattern of use and we will ask the right questions rather than the generic ones.",
     "Beides ändert das Risiko, das ein Versicherer bepreisen soll. Nennen Sie das Nutzungsmuster, wir stellen die richtigen Fragen statt der generischen."),
    ("That is the normal starting point, not an unusual one. Tell us about the property and your situation below and we will come back with a clear, written answer — what we think you need, what we can currently arrange, and what to look into next if it is outside what we can help with today.",
     "Das ist der normale Ausgangspunkt, kein ungewöhnlicher. Schildern Sie unten Immobilie und Lage. Wir antworten schriftlich klar: was wir für nötig halten, was wir derzeit vermitteln können, und was als Nächstes zu klären ist, wenn es außerhalb dessen liegt, wobei wir heute helfen können."),
    ("Adler & Rochefort is the trading name of Ownizo, Unipessoal Lda., an insurance intermediary registered with Portugal’s insurance supervisor, the ASF (Autoridade de Supervisão de Seguros e Fundos de Pensões), under no. 425591790/3. We have spent several years arranging insurance in English for expats, foreign residents and property owners in Portugal, and we are extending that service to cover Spain.",
     "Adler & Rochefort ist die Handelsmarke der Ownizo, Unipessoal Lda., Versicherungsmakler, registriert bei der portugiesischen Aufsicht ASF (Autoridade de Supervisão de Seguros e Fundos de Pensões), Nr. 425591790/3. Seit mehreren Jahren vermitteln wir Versicherungen für Expats, internationale Mandanten und Eigentümer in Portugal — denselben Service erweitern wir auf Spanien."),
    ("The questions, the explanation of what a policy covers, and the correspondence. We do not ask you to read a Spanish policy wording unassisted.",
     "Die Fragen, die Erläuterung, was eine Police deckt, und die Korrespondenz. Wir erwarten nicht, dass Sie einen spanischen Wortlaut allein lesen."),
    ("A straight answer, not a sales pitch.", "Eine klare Antwort, kein Verkaufsgespräch."),
    ("If a case falls outside what we can currently arrange in Spain, we say so rather than take a lead we cannot service.",
     "Liegt ein Fall außerhalb dessen, was wir in Spanien derzeit vermitteln können, sagen wir das — statt eine Anfrage anzunehmen, die wir nicht bedienen können."),
    ("One point of contact.", "Ein Ansprechpartner."),
    ("The same team that already handles home and landlord cover for international clients in Portugal.",
     "Dasselbe Team, das für internationale Mandanten in Portugal bereits Haus und Vermietung betreut."),
    ("Adler " + A + " Rochefort operates in Spain on a cross-border basis from its Portuguese registration, under the EU framework that allows an insurance intermediary authorised in one EU/EEA state to offer services in another. We do not hold a separate Spanish licence, we do not have a Spanish office, and we do not claim to compare the whole Spanish insurance market — only what we say plainly, above, that we can currently arrange.",
     "Adler " + A + " Rochefort ist in Spanien im Dienstleistungsverkehr von der portugiesischen Registrierung aus tätig, nach dem EU-Rahmen, der einem in einem EU/EWR-Staat zugelassenen Vermittler Leistungen in einem anderen erlaubt. Wir haben keine gesonderte spanische Zulassung, kein spanisches Büro, und wir behaupten nicht, den ganzen spanischen Markt zu vergleichen — nur das, was wir oben klar sagen, derzeit vermitteln zu können."),
    ("Tell us about the property and your situation. We will come back with a written answer on what applies to you and what we can currently arrange.",
     "Schildern Sie Immobilie und Lage. Wir antworten schriftlich, was auf Sie zutrifft und was wir derzeit vermitteln können."),
    ("Tell us who needs cover and where you are in the move. We do not ask for medical details here — that stays with the insurer, as part of underwriting.",
     "Sagen Sie uns, wer versichert werden soll und wo Sie im Umzug stehen. Medizinische Details erheben wir hier nicht — die bleiben beim Versicherer, in der Risikoprüfung."),
    ("Tell us about the property and how it is let. Long-term versus short-term changes the answer more than anything else on this form.",
     "Schildern Sie die Immobilie und die Vermietung. Langzeit oder Kurzzeit ändert die Antwort mehr als alles andere auf diesem Formular."),
    ("Living in Spain", "Leben in Spanien"),
    ("Buying a property", "Eine Immobilie kaufen"),
    ("Owning a home", "Ein Haus besitzen"),
    ("A second home", "Ein Zweitwohnsitz"),
    ("Renting out a property", "Eine Immobilie vermieten"),
    ("Owning property without living in Spain", "Besitz ohne Wohnsitz in Spanien"),
    ("Private health insurance", "Private Krankenversicherung"),
    ("A car", "Ein Auto"),
    ("A mortgage", "Eine Hypothek"),
    ("Protecting your family", "Die Familie schützen"),
    ("Multiple or higher-value risks", "Mehrere oder höherwertige Risiken"),
    ("Buying before you move", "Kaufen vor dem Umzug"),
    ("Renting while you settle in", "Mieten, während Sie ankommen"),
    ("The property will sit empty for a while", "Die Immobilie steht eine Weile leer"),
    ("You are not resident yet, but you own the property already", "Noch nicht Resident, die Immobilie gehört Ihnen aber schon"),
    ("You live in the UK", "Sie leben im Vereinigten Königreich"),
    ("You live elsewhere in Europe", "Sie leben anderswo in Europa"),
    ("You live outside Europe", "Sie leben außerhalb Europas"),
    ("The property is used seasonally, or let out when you are away", "Saisonale Nutzung oder Vermietung in Ihrer Abwesenheit"),
    ("Moving to Spain", "Umzug nach Spanien"),
    ("Already an international resident", "Bereits internationaler Resident"),
    ("Foreign professionals and the self-employed", "Fachkräfte und Selbstständige aus dem Ausland"),
    ("Non-Spanish-speaking clients", "Mandanten ohne Spanisch"),
    ("The questions, the comparison and the policy explanation are all in English.",
     "Fragen, Vergleich und Erläuterung der Police laufen auf Deutsch."),
    ]
    # more health/home/car paragraphs added in extra()


def extra_product():
    return [
    ("Moving to Spain, or already there and thinking about private cover? We help you work out what actually applies to your situation — individual or family, resident or arriving soon — and tell you honestly what can currently be arranged.",
     "Umzug nach Spanien, oder schon dort und private Deckung im Blick? Wir klären, was zu Ihrer Lage wirklich passt — einzeln oder Familie, resident oder bald ankommend — und sagen ehrlich, was sich derzeit vermitteln lässt."),
    ("Spain has a broad, tax-funded public healthcare system, and a large private sector that operates alongside it rather than instead of it. Whether you can register with the public system, and on what basis, depends on your residence status and how you entered it — that is not something this page can answer for you in general terms, and it is worth checking directly with the relevant authority once your situation is clear.",
     "Spanien hat ein breites, steuerfinanziertes öffentliches Gesundheitssystem und einen großen Privatsektor daneben, nicht statt dessen. Ob und wie Sie sich öffentlich anmelden können, hängt vom Aufenthalt ab — das beantwortet diese Seite nicht pauschal. Das klären Sie bei der zuständigen Stelle, sobald Ihre Lage klar ist."),
    ("What private medical insurance adds is not a replacement for the public system but a different way in: faster access to a specialist, a choice of clinic or hospital, treatment in English where the insurer’s network supports it, and — for some visa and residence routes — documentation that the application process asks for. Not everyone needs it, and not every foreign resident has identical access to the public system, so we start from your situation rather than a blanket assumption.",
     "Private Krankenversicherung ersetzt das öffentliche System nicht, sie ist ein anderer Zugang: schneller zum Facharzt, Wahl der Klinik, Behandlung auf Deutsch oder Englisch wo das Netz es hergibt, und — auf manchen Visa- und Aufenthaltswegen — der Nachweis, den das Verfahren verlangt. Nicht jeder braucht sie, und nicht jeder ausländische Resident hat denselben öffentlichen Zugang. Wir starten bei Ihrer Lage, nicht bei einer Pauschalannahme."),
    ("People come to this page from several different situations. Say which one is closest and we will ask the right follow-up questions rather than the generic ones.",
     "Die Leute kommen aus verschiedenen Lagen auf diese Seite. Sagen Sie, was am nächsten kommt — wir stellen die richtigen Nachfragen, nicht die generischen."),
    ("Whether cover needs to be in place before you arrive depends on your route — see the visa and residence note below.",
     "Ob Deckung vor der Ankunft stehen muss, hängt vom Weg ab — siehe den Hinweis zu Visum und Aufenthalt unten."),
    ("Reviewing what you have, or arranging cover for the first time now that you are settled.",
     "Prüfen, was Sie haben, oder zum ersten Mal Deckung einrichten, jetzt da Sie sesshaft sind."),
    ("Individual cover, arranged the same way regardless of who employs you.",
     "Einzeldeckung, unabhängig davon, wer Sie beschäftigt."),
    ("Adults and children together, or as separate policies — see the families section below.",
     "Erwachsene und Kinder gemeinsam oder getrennt — siehe den Abschnitt Familien unten."),
    ("See the dedicated section below — entitlement and requirements vary by circumstances, not by age alone.",
     "Siehe den eigenen Abschnitt unten — Anspruch und Anforderungen hängen von den Umständen ab, nicht vom Alter allein."),
    ("What a specific plan actually includes is set by the insurer and the plan, never by this page — the categories below are what plans in this market commonly address, not a guarantee of what any one policy contains:",
     "Was ein konkreter Tarif enthält, setzt der Versicherer — nie diese Seite. Die Kategorien unten sind, was Tarife in diesem Markt häufig abdecken, keine Garantie für eine bestimmte Police:"),
    ("GP and primary care.", "Hausarzt und Grundversorgung."),
    ("Access to a general practitioner, in-network or via consultation, depending on the plan.",
     "Zugang zum Hausarzt, im Netz oder per Konsultation, je nach Tarif."),
    ("Referral to specialist consultations, usually within the insurer’s network.",
     "Überweisung zum Facharzt, meist im Netz des Versicherers."),
    ("Diagnostic tests.", "Diagnostik."),
    ("Scans, bloodwork and imaging — scope and any pre-authorisation requirement vary by plan.",
     "Bildgebung, Blutwerte — Umfang und etwaige Vorabgenehmigung je nach Tarif."),
    ("Hospital treatment and surgery.", "Krankenhaus und Operation."),
    ("Typically the core of a private medical plan, with sub-limits that differ by insurer.",
     "Typischer Kern einer privaten Krankenpolice, mit Untergrenzen je Versicherer."),
    ("Emergency and outpatient care.", "Notfall und ambulant."),
    ("Included on most plans, though territorial scope and network conditions differ.",
     "In den meisten Tarifen enthalten, Territorialität und Netzbedingungen unterscheiden sich."),
    ("Maternity, where available.", "Schwangerschaft, wo verfügbar."),
    ("Not universal, and frequently subject to a waiting period — confirm before assuming it is included.",
     "Nicht selbstverständlich, oft mit Wartezeit — nicht unterstellen, dass es enthalten ist."),
    ("Mental health, where available.", "Psychische Gesundheit, wo verfügbar."),
    ("Scope varies significantly by insurer and plan; worth checking explicitly rather than assuming parity with physical health cover.",
     "Der Umfang unterscheidet sich stark; lieber nachfragen, statt Gleichstand mit der körperlichen Deckung anzunehmen."),
    ("Physiotherapy, where available.", "Physiotherapie, wo verfügbar."),
    ("Often included with session limits rather than unlimited access.",
     "Oft mit Sitzungslimit, nicht unbegrenzt."),
    ("Some plans charge a small copayment per consultation or procedure and cost less as a result; others are written with no copayment and a correspondingly different price. Neither is universally \"better\" — it depends on how often you expect to use the cover and what monthly cost you would rather carry instead. We set out both options where the insurer offers them, rather than defaulting to one.",
     "Manche Tarife verlangen eine kleine Zuzahlung je Termin und sind dafür günstiger; andere ohne Zuzahlung und mit anderem Preis. Keines ist pauschal „besser“ — es hängt davon ab, wie oft Sie die Deckung nutzen und welche Monatsprämie Sie lieber tragen. Wir legen beide Optionen vor, wo der Versicherer sie bietet."),
    ("Private insurers work with defined networks of clinics, hospitals and specialists rather than every provider in Spain. Which hospitals and doctors you can access depends on the insurer, the plan and, often, the region — we do not claim access to a specific hospital or network here, because that claim only means anything against an actual policy wording. Ask us for the network detail once we know which insurer and plan is realistic for your case.",
     "Private Versicherer arbeiten mit festgelegten Netzen, nicht mit jedem Anbieter in Spanien. Welche Kliniken und Ärzte Sie erreichen, hängt von Versicherer, Tarif und oft der Region ab. Wir behaupten hier keinen Zugang zu einem bestimmten Haus — das gilt nur gegen einen konkreten Wortlaut. Netzdetails, sobald klar ist, welcher Versicherer und Tarif für Ihren Fall realistisch ist."),
    ("Insurers ask medical questions before offering health cover, and how they treat a pre-existing condition is an underwriting decision that varies by insurer and by condition — some exclude it, some cover it after a delay, some price around it. We cannot promise acceptance or promise that a specific condition will be covered before an insurer has actually assessed the case.",
     "Versicherer stellen vor der Annahme Gesundheitsfragen. Wie eine Vorerkrankung behandelt wird, ist eine Zeichnungsentscheidung: Ausschluss, Wartezeit oder Preis. Wir können Annahme oder Deckung einer bestimmten Erkrankung nicht versprechen, bevor ein Versicherer den Fall geprüft hat."),
    ("Declare medical history accurately at application. An inaccurate declaration is one of the most common reasons a claim is later declined — understating something to get a better price almost always costs more than it saves.",
     "Geben Sie die Krankengeschichte bei Antrag korrekt an. Eine ungenaue Angabe ist einer der häufigsten Gründe, warum ein Schaden später abgelehnt wird — Untertreiben für einen besseren Preis kostet fast immer mehr, als es spart."),
    ("Some benefits — maternity is a common example — carry a waiting period before they become active, and some plans apply a general waiting period to new members. We do not state a universal number here because it depends on the insurer and the plan; we will tell you the actual figure once we know which product is being quoted.",
     "Manche Leistungen — Schwangerschaft ist ein häufiges Beispiel — haben eine Wartezeit, und manche Tarife eine allgemeine für neue Mitglieder. Eine universale Zahl nennen wir hier nicht, sie hängt von Versicherer und Tarif ab; die konkrete Zahl, sobald klar ist, welches Produkt angeboten wird."),
    ("This is the section that needs the most care, and where we are most likely to say \"check with the relevant authority\" rather than state a rule. Different residence and visa routes — a non-lucrative visa, a digital nomad visa, an EU citizen exercising free movement, a student route — can carry different requirements for proof of health cover, and those requirements are set and interpreted by the consulate or immigration authority handling the application, not by us.",
     "Dieser Abschnitt braucht die meiste Vorsicht — hier sagen wir eher „prüfen Sie bei der zuständigen Stelle“, statt eine Regel zu behaupten. Unterschiedliche Aufenthalts- und Visawege können unterschiedliche Nachweise verlangen. Die Anforderungen setzt und liest die Behörde, die den Antrag führt, nicht wir."),
    ("We do not promise that any policy will be accepted by a consulate or immigration authority simply because it is described as \"visa insurance.\" Requirements depend on the route, the applicant’s circumstances and the authority handling the case, and they can change. Confirm the current position with the relevant consulate or immigration authority before you buy, and read",
     "Wir versprechen nicht, dass eine Police von Konsulat oder Ausländerbehörde angenommen wird, nur weil sie als „Visa-Versicherung“ beschrieben wird. Die Anforderungen hängen vom Weg, von den Umständen und von der Behörde ab, und sie können sich ändern. Klären Sie den aktuellen Stand bei der zuständigen Stelle, bevor Sie kaufen."),
    ("health insurance for Spanish visas and residency", "Krankenversicherung für spanische Visa und den Aufenthalt"),
    ("for what to check.", "was zu prüfen ist."),
    ("What we can do is help you get a policy in place with enough lead time, and tell you plainly what the plan does and does not include — the confirmation that it satisfies a specific application belongs with the authority processing it, not with us.",
     "Was wir können: eine Police rechtzeitig einrichten und klar sagen, was der Tarif enthält und was nicht. Die Bestätigung, dass sie einem konkreten Antrag genügt, gehört zur Behörde, die ihn führt — nicht zu uns."),
    ("A domestic private medical plan in Spain is built around Spanish providers and Spanish territory. Broader international private medical insurance can extend geographic scope beyond Spain, at a different price point. Which is right depends on where you actually live, whether you travel or split time between countries, the providers you want access to, and budget — not on one being categorically better than the other. Tell us your situation and we will say honestly which shape of product it points to, and whether both are realistic options for your case today.",
     "Ein spanischer Inlandstarif ist um spanische Anbieter und spanisches Gebiet gebaut. Breitere internationale Krankenversicherung weitet den geografischen Umfang, zu einem anderen Preis. Was passt, hängt davon ab, wo Sie wirklich leben, ob Sie reisen oder Zeit teilen, welche Häuser Sie wollen, und vom Budget — nicht davon, dass eines pauschal besser wäre. Schildern Sie die Lage, wir sagen ehrlich, welche Form realistischer ist."),
    ("Cover for a family usually means separate underwriting per person even when it is billed as one policy — a child's plan and an adult's plan are not priced or underwritten identically, and paediatric care, where included, is typically a distinct benefit rather than an extension of adult cover. Maternity, where relevant and where available, is worth raising early given the waiting periods noted above. We ask about everyone to be insured individually rather than quote a household as a single unit.",
     "Familiendeckung heißt meist einzelne Risikoprüfung je Person, auch wenn eine Police abgerechnet wird. Kinder- und Erwachsenentarif sind nicht identisch gezeichnet; pädiatrische Leistungen, wo enthalten, sind ein eigener Baustein. Schwangerschaft, wo relevant und verfügbar, früh ansprechen wegen der Wartezeiten. Wir fragen zu jeder Person einzeln, statt den Haushalt als Einheit zu quotieren."),
    ("Private health insurance is not a universal legal requirement for every foreign retiree in Spain — whether it is required, and what public healthcare entitlement looks like, depends on your specific residence and pension circumstances, including whether a form such as the EU’s S1 applies to your case. We are not the right source for that determination; what we can help with is the private cover itself, once you know what you actually need it to do alongside whatever public entitlement applies to you.",
     "Private Krankenversicherung ist nicht für jeden ausländischen Rentner in Spanien gesetzlich vorgeschrieben. Ob sie nötig ist und wie der öffentliche Anspruch aussieht, hängt von Aufenthalt und Rente ab — einschließlich, ob ein Formular wie die S1 greift. Das entscheiden nicht wir. Wobei wir helfen: die private Deckung selbst, sobald klar ist, was sie neben dem öffentlichen Anspruch tun soll."),
    ("We do not publish average health insurance costs for Spain here — a number picked up for its SEO value rather than checked against a real quote is worse than no number at all. What genuinely moves the price:",
     "Durchschnittsprämien für Spanien veröffentlichen wir hier nicht — eine Zahl fürs Ranking statt aus einem echten Angebot ist schlechter als keine. Was den Preis wirklich bewegt:"),
    ("The single largest factor on most personal health plans.",
     "Der größte Faktor in den meisten privaten Krankenpolicen."),
    ("Available networks and regional pricing both vary.",
     "Verfügbare Netze und regionale Preise unterscheiden sich."),
    ("Insurer and plan", "Versicherer und Tarif"),
    ("There is no single \"Spanish health policy\" — products differ meaningfully between insurers.",
     "Es gibt nicht „die“ spanische Krankenpolice — Produkte unterscheiden sich zwischen Versicherern spürbar."),
    ("A plan with copayments is typically cheaper than an equivalent plan without them.",
     "Ein Tarif mit Zuzahlung ist typischerweise günstiger als ein vergleichbarer ohne."),
    ("Medical underwriting", "Medizinische Risikoprüfung"),
    ("Declared health history affects both price and terms.",
     "Angegebene Krankengeschichte wirkt auf Preis und Bedingungen."),
    ("Number of people insured", "Anzahl der versicherten Personen"),
    ("Each person is underwritten individually, as noted under Families above.",
     "Jede Person wird einzeln gezeichnet, siehe Familien oben."),
    ("Geographic scope", "Geografischer Umfang"),
    ("Domestic Spanish cover versus broader international scope changes the price materially.",
     "Spanische Inlandsdeckung gegenüber weiterem internationalen Umfang ändert den Preis spürbar."),
    ("Benefits selected", "Gewählte Leistungen"),
    ("Maternity, dental extensions and higher outpatient limits all move the premium.",
     "Schwangerschaft, Zahn-Erweiterungen und höhere ambulante Limits bewegen die Prämie."),
    ("Who needs to be covered.", "Wer versichert werden soll."),
    ("Ages of everyone to be insured, and whether it is an individual or family policy.",
     "Alter aller zu Versichernden, und ob Einzel- oder Familienpolice."),
    ("Where you are, or will be.", "Wo Sie sind oder sein werden."),
    ("Current location and, if different, where in Spain you are moving to or already live.",
     "Derzeitiger Ort und, falls anders, wo in Spanien Sie hinziehen oder bereits leben."),
    ("Already resident, or working to a moving date — and whether a visa or residence application is involved.",
     "Bereits Resident oder mit Umzugstermin — und ob Visum oder Aufenthalt eine Rolle spielt."),
    ("What you have now.", "Was Sie jetzt haben."),
    ("Any existing health cover, domestic or international, and its renewal date if applicable.",
     "Bestehende Krankenversicherung, inland oder international, und das Verlängerungsdatum falls vorhanden."),
    ("We ask for this much and no more at quote stage — we do not collect detailed medical history through the website form. Any medical questions an insurer needs answered are handled directly with the insurer as part of underwriting, not gathered upfront on a generic web form.",
     "Mehr verlangen wir in der Angebotsstufe nicht — detaillierte Krankengeschichte erheben wir nicht über das Webformular. Medizinische Fragen des Versicherers laufen direkt mit ihm in der Risikoprüfung, nicht vorab auf einem generischen Formular."),
    ("Whether cover needs to be in place before you arrive depends on your route — see the visa and residence note below.",
     "Ob Deckung vor der Ankunft stehen muss, hängt vom Weg ab — siehe Visum und Aufenthalt unten."),
    ]


def polish_file(path: Path) -> None:
    html = path.read_text(encoding="utf-8")
    orig = html
    for old, new in BLOG_TO_CLUSTER:
        html = html.replace(old, new)
    pairs = T() + body_pairs() + extra_product()
    pairs.sort(key=lambda x: len(x[0]), reverse=True)
    for old, new in pairs:
        html = html.replace(old, new)
    html = strip_blog_cards(html)
    # leftover mixed
    html = html.replace("Nicht-resident Eigentümerhip", "Nicht-resident Eigentum")
    html = html.replace("Get a Autoversicherung Quote", "Autoversicherung anfragen")
    html = html.replace("Get a Krankenversicherung Quote", "Krankenversicherung anfragen")
    html = html.replace("<strong>Health insurance</strong>", "<strong>Krankenversicherung</strong>")
    html = html.replace("<strong>Home insurance</strong>", "<strong>Hausversicherung</strong>")
    html = html.replace("<strong>Landlord insurance</strong>", "<strong>Vermieterversicherung</strong>")
    html = html.replace("<strong>Car insurance</strong>", "<strong>Autoversicherung</strong>")
    html = html.replace("<strong>Life insurance</strong>", "<strong>Lebensversicherung</strong>")
    html = html.replace("<strong>Private clients</strong>", "<strong>Private Clients</strong>")
    html = html.replace("<strong>Health</strong>", "<strong>Krankenversicherung</strong>")
    if html != orig:
        path.write_text(html, encoding="utf-8")
        print("  updated", path.parent.name, "delta", len(html) - len(orig))
    else:
        print("  unchanged", path.parent.name)


def leftover_count(path: Path) -> int:
    html = path.read_text(encoding="utf-8")
    html = re.sub(r"<script[\s\S]*?</script>", " ", html)
    html = re.sub(r"<style[\s\S]*?</style>", " ", html)
    n = 0
    for m in re.finditer(r">([^<]{20,})<", html):
        t = " ".join(m.group(1).split())
        if re.search(r"\b(the|and|your|for|with|this|insurance|cover|quote|already|typically|please)\b", t, re.I):
            n += 1
    return n


def main():
    print("Polishing DE Spain pages (PT product pages not touched)")
    for d in sorted((ROOT / "public/de").glob("*spanien*")):
        polish_file(d / "index.html")
        print("    leftover-ish", leftover_count(d / "index.html"))


if __name__ == "__main__":
    main()
